const test=require('node:test'),a=require('node:assert/strict');
const L=require('../scripts/english-rpg/logic.cjs'),M=require('../scripts/english-rpg/maps.cjs');
function win(p,id){const b=L.beginBattle(p,id,()=>0);a.ok(b);let result;for(let guard=0;guard<100&&b.status==='active';guard++){const q=L.questions.find(q=>q.id===b.question);result=L.answerBattle(p,b,q.answer);if(b.status==='active')L.advanceBattle(p,b,()=>0)}a.equal(b.status,'won');return {b,result};}
function talk(p){const q=L.currentQuest(p);p.map=q.map;return L.finishQuest(p,{type:'talk',target:q.target,quest:q.id});}
test('12 ordered quests provide a complete story, three stars and a festival ending',()=>{for(const weapon of ['iron','wand']){const p=L.fresh();a.ok(talk(p));a.equal(p.gold,60);p.map='smith';a.ok(L.purchase(p,weapon,'weapon').ok);a.equal(p.step,2);p.map='forest';win(p,'slime-a');const {result}=win(p,'slime-b');a.equal(result.quest.quest.id,'sun');a.deepEqual(p.stars,['sun']);a.ok(talk(p));a.ok(L.canEnter(p,'coast'));a.ok(talk(p));p.map='coast';win(p,'crab');win(p,'water');a.ok(talk(p));a.ok(L.canEnter(p,'mountain'));a.ok(talk(p));a.equal(L.canEnter(p,'ruins'),false);a.ok(L.finishQuest(p,{type:'interact',target:'key-chest'}));a.ok(L.canEnter(p,'ruins'));p.map='ruins';win(p,'guardian');a.equal(p.stars.length,3);p.map='village';a.ok(L.finishQuest(p,{type:'interact',target:'beacon'}));a.ok(p.festival);a.ok(talk(p));a.equal(p.step,12);a.equal(L.currentQuest(p),null);a.ok(p.gold>=240);a.equal(L.finishQuest(p,{type:'talk',target:'mia',quest:'finale'}),null);p.map='tailor';a.ok(L.purchase(p,'festival','outfit').ok);a.equal(p.outfit,'festival');a.deepEqual(L.sanitize(JSON.parse(JSON.stringify(p))).stars,p.stars)}});
test('gold purchases are atomic, duplicate purchases cannot deduct gold, owned equipment affects combat',()=>{const p=L.fresh();p.map='smith';p.gold=39;const before=JSON.stringify(p);a.equal(L.purchase(p,'iron','weapon').ok,false);a.equal(JSON.stringify(p),before);p.gold=150;const base=L.stats(p).attack;a.ok(L.purchase(p,'iron','weapon').ok);a.equal(p.gold,110);a.equal(L.stats(p).attack,base+8);a.equal(L.purchase(p,'iron','weapon').ok,false);a.equal(p.gold,110);a.equal(L.purchase(p,'rose','weapon').ok,false);a.equal(L.equip(p,'starblade'),false);p.map='tailor';a.ok(L.purchase(p,'rose','outfit').ok);a.equal(L.stats(p).defense,2);a.equal(L.purchase(p,'festival','outfit').ok,false)});
test('battle validates options, wrong answers hurt only player, correct answers hurt monster, rewards occur once',()=>{const p=L.fresh();p.map='forest';const b=L.beginBattle(p,'slime-a',()=>0),q=L.questions.find(q=>q.id===b.question),hp=b.hp;a.equal(L.answerBattle(p,b,'made-up answer'),null);a.equal(b.round,0);const wrong=L.answerBattle(p,b,q.wrong[0]);a.equal(wrong.correct,false);a.equal(b.hp,hp);a.equal(p.hp,79);a.equal(p.mistakes[q.id],1);a.equal(L.answerBattle(p,b,q.answer),null);L.advanceBattle(p,b,()=>0);const next=L.questions.find(q=>q.id===b.question);const right=L.answerBattle(p,b,next.answer);a.equal(right.correct,true);a.ok(b.hp<hp);while(b.status==='active'){L.advanceBattle(p,b,()=>0);L.answerBattle(p,b,L.questions.find(q=>q.id===b.question).answer);}const gold=p.gold;a.equal(L.answerBattle(p,b,q.answer),null);a.equal(p.gold,gold);a.equal(p.battles,1)});
test('defeat has no currency loss and a free rest restores HP',()=>{const p=L.fresh();p.map='forest';p.gold=50;const b=L.beginBattle(p,'slime-a',()=>0),q=L.questions.find(q=>q.id===b.question);while(b.status==='active'){L.answerBattle(p,b,L.questions.find(q=>q.id===b.question).wrong[0]);if(b.status==='active')L.advanceBattle(p,b,()=>0);}a.equal(b.status,'lost');a.equal(p.hp,0);a.equal(p.gold,50);a.equal(L.beginBattle(p,'slime-b'),null);L.rest(p);a.equal(p.hp,L.stats(p).maxHp)});
test('legacy progress does not skip the story or unlock paid gear, malformed saves are bounded',()=>{const p=L.sanitize(null,{avatar:'male-a',completed:['mountain-station'],coins:900});a.equal(p.avatar,'jun');a.equal(p.step,0);a.equal(p.gold,0);a.equal(L.canEnter(p,'mountain'),false);const s=L.sanitize({gold:Infinity,xp:NaN,hp:9999,step:-8,map:'ruins',owned:['oops','traveler'],weapon:'starblade'});a.equal(s.gold,0);a.equal(s.xp,0);a.equal(s.hp,90);a.equal(s.map,'village');a.equal(s.weapon,'wood');a.equal(s.step,0)});
test('partial state, chest use and learned/missed phrases survive reload',()=>{const p=L.fresh();p.step=8;p.map='lodge';p.choices['forest-chest']=true;p.learned['word-2']=3;p.mistakes['word-3']=2;p.gold=87;p.xp=181;p.hp=42;const s=L.sanitize(JSON.parse(JSON.stringify(p)));a.equal(s.map,'lodge');a.equal(s.key,false);a.equal(s.hp,42);a.equal(s.gold,87);a.ok(s.choices['forest-chest']);a.equal(s.learned['word-2'],3);a.equal(s.mistakes['word-3'],2)});
test('English difficulty grows with level and unseen / missed prompts are prioritized',()=>{const p=L.fresh();a.ok(L.pool(p).every(q=>q.tier===1));const low=L.pool(p).reduce((n,q)=>n+q.answer.split(' ').length,0)/L.pool(p).length;p.xp=1100;const high=L.pool(p).reduce((n,q)=>n+q.answer.split(' ').length,0)/L.pool(p).length;a.ok(high>low*2);a.ok(L.pool(p).every(q=>q.tier>=7));const q=L.pool(p)[2];p.mistakes[q.id]=3;a.equal(L.nextQuestion(p,[],()=>0).id,q.id);a.notEqual(L.nextQuestion(p,[q.id],()=>0).id,q.id);for(const q of L.questions){a.equal(new Set([q.answer,...q.wrong]).size,3);a.ok(q.prompt&&q.cue&&q.meaning)}});
test('travel gates and quest target prevent out-of-order completion',()=>{const p=L.fresh();a.equal(L.canEnter(p,'coast'),false);a.equal(L.canEnter(p,'ruins'),false);a.equal(L.finishQuest(p,{type:'interact',target:'beacon'}),null);a.equal(L.finishQuest(p,{type:'talk',target:'lucy',quest:'letter'}),null);p.map='forest';a.equal(L.finishQuest(p,{type:'talk',target:'mia',quest:'letter'}),null);a.equal(L.beginBattle(p,'guardian'),null)});
test('every map entrance and reachable quest interaction has a valid path without crossing walls',()=>{for(const map of Object.values(M.maps)){a.equal(M.blocked(map,...map.spawn),false,map.name+' spawn');for(const e of map.entities){if(e.type==='door'){a.ok(M.maps[e.to],e.id);a.equal(M.blocked(M.maps[e.to],...e.spawn),false,e.id+' destination')}const point=(map.shop&&e.type==='npc')||e.id==='lucy'?{...e,y:e.y+3}:e;const path=M.approach(map,point,{x:map.spawn[0],y:map.spawn[1]});a.ok(path,`${map.name} ${e.id} should be reachable`);for(const p of path.path)a.equal(M.blocked(map,p.x,p.y),false)}}});
