const {webkit}=require('playwright'),assert=require('assert');
(async()=>{const b=await webkit.launch();try{const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('file://'+require('path').resolve(__dirname,'../english-travel-3d.html'));await p.locator('[data-cmd=species][data-arg=dog]').click();await p.locator('#adoptName').fill('Biscuit');await p.locator('[data-cmd=adopt]').click();
for(const [cmd,title] of [['pantry','What would you like?'],['toys','Let’s play together'],['rest','Time for a good sleep'],['clinic','Sunny Vet Clinic']]){await p.locator('#needs [data-cmd='+cmd+']').click();assert.equal(await p.locator('#sheetTitle').textContent(),title);await p.locator('#sheetClose').click();}
await p.evaluate(()=>{const k='little-lives-v3',s=JSON.parse(localStorage.getItem(k));s.food=25;s.energy=25;localStorage.setItem(k,JSON.stringify(s))});await p.reload();assert.equal(await p.locator('#needs .low').count(),2);await p.locator('[data-nav=shop]').click();assert.match(await p.locator('.penalty').textContent(),/×2/);assert.match(await p.locator('[data-cmd=buy][data-arg=fish]').textContent(),/44 G/);await p.locator('#sheetClose').click();
await p.locator('[data-nav=out]').click();await p.locator('[data-cmd=place][data-arg=school]').click();await p.locator('[data-cmd=begin][data-arg=school-first]').click();await p.locator('#translateButton').click();assert.equal(await p.locator('#translation').textContent(),'좋은 아침이에요!');
await p.evaluate(()=>{window.KittySpeech.stop();window.KittySpeech.speak=()=>new Promise(r=>window.finishVoice=r);window.KittySpeech.wrong=()=>window.beeps=(window.beeps||0)+1});await p.locator('[data-cmd=answer][data-arg="1"]').click();assert.equal(await p.evaluate(()=>window.beeps),1);assert.equal(await p.locator('.choices .wrong').count(),1);assert.equal(await p.locator('#choices button:disabled').count(),3);await p.evaluate(()=>finishVoice('ended'));await p.locator('[data-cmd=answer][data-arg="0"]').click();assert.equal(await p.locator('#nextLine').isDisabled(),true);await p.waitForTimeout(300);assert.equal(await p.locator('#nextLine').isDisabled(),true);await p.evaluate(()=>finishVoice('ended'));await p.locator('#nextLine').click();assert.match(await p.locator('#choices').textContent(),/My dog’s name is Biscuit/);assert.equal(await p.locator('#translation').isHidden(),true);await p.locator('#episodeBack').click();await p.locator('[data-cmd=leave]').click();
await p.evaluate(()=>Math.random=()=>.999);
for(const id of ['plane','bricks','pairs']){await p.locator('[data-nav=out]').click();await p.locator('[data-cmd=arcade]').click();await p.locator('[data-cmd=minigame][data-arg='+id+']').click();await p.locator('#arcadeStart').click();if(id!=='pairs'){await p.waitForTimeout(200);assert.equal(await p.locator('canvas').count(),1);await p.keyboard.press('ArrowLeft');}else{const before=await p.evaluate(()=>JSON.parse(localStorage.getItem('little-lives-v3')));for(let i=0;i<6;i++)await p.locator('.pair-card').nth(i).click();assert.match(await p.locator('#arcadeResult').textContent(),/15 G/);const after=await p.evaluate(()=>JSON.parse(localStorage.getItem('little-lives-v3')));assert.equal(after.gold,before.gold+15);assert.equal(after.xp,before.xp+20);await p.locator('#arcadeStart').click();await p.locator('#arcadeStart').click();for(let i=0;i<6;i++)await p.locator('.pair-card').nth(i).click();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('little-lives-v3')).gold),after.gold);}await p.locator('#sheetClose').click();}
await p.screenshot({path:'/tmp/kitty-v5-home.png'});assert.deepEqual(errors,[]);console.log('PASS WebKit: gauge shortcuts, red needs, price penalty, Korean translation, dog name, wrong beep, full speech lock, three arcade starts/cleanup');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
