// Original characters, world and pixel artwork for Starword. No external game assets.
const items = [
 {id:'traveler',slot:'outfit',name:'여행자의 옷',price:0,def:0,color:'#728caf',trim:'#dfbf81',style:'tunic',desc:'첫 모험을 함께하는 옷'},
 {id:'rose',slot:'outfit',name:'장미 망토',price:35,def:2,color:'#bf617e',trim:'#ffdbb1',style:'cape',desc:'분홍 망토 · 방어 +2'},
 {id:'ranger',slot:'outfit',name:'숲지기 의상',price:75,def:4,color:'#458c77',trim:'#eac977',style:'ranger',desc:'깃털 모자 · 방어 +4'},
 {id:'mage',slot:'outfit',name:'별빛 마법사',price:130,def:6,color:'#7b65bd',trim:'#f5d77f',style:'mage',desc:'별 모자와 로브 · 방어 +6'},
 {id:'knight',slot:'outfit',name:'달빛 기사',price:200,def:9,color:'#90aeba',trim:'#eee4bc',style:'armor',desc:'은빛 갑옷 · 방어 +9'},
 {id:'festival',slot:'outfit',name:'축제의 영웅',price:240,def:12,color:'#f1ece0',trim:'#cf9f46',style:'hero',festival:true,desc:'축제를 되찾은 증표 · 방어 +12'},
 {id:'wood',slot:'weapon',name:'나무 검',price:0,atk:0,color:'#9b7152',style:'sword',desc:'기본 무기'},
 {id:'iron',slot:'weapon',name:'철 검',price:40,atk:8,color:'#c9d9df',style:'sword',desc:'정답 공격력 +8'},
 {id:'wand',slot:'weapon',name:'별 지팡이',price:45,atk:9,color:'#a386d2',style:'wand',desc:'별빛 마법 · 공격력 +9'},
 {id:'silver',slot:'weapon',name:'은빛 검',price:110,atk:17,color:'#e7f9ff',style:'sword',desc:'정답 공격력 +17'},
 {id:'sunstaff',slot:'weapon',name:'태양 지팡이',price:170,atk:24,color:'#ecc867',style:'wand',desc:'황금빛 마법 · 공격력 +24'},
 {id:'starblade',slot:'weapon',name:'별의 검',price:260,atk:34,color:'#9ee9de',style:'star',desc:'별빛을 담은 검 · 공격력 +34'}
];
const line=(en,ko,answer,meaning)=>({en,ko,answer,meaning});
const quests=[
 {id:'letter',chapter:1,title:'Mia에게 축제의 편지 받기',map:'village',target:'mia',type:'talk',name:'사라진 별빛',context:'폭풍 뒤, 축제를 밝힐 별 세 개가 사라졌어. 함께 찾아 줄래?',lines:[line('Can you help me?','나를 도와줄래?','I can help.','내가 도와줄게.')],gold:60,xp:20,outcome:'모험 지원금으로 무기를 준비하자.'},
 {id:'gear',chapter:1,title:'무기점에서 새 무기 사기',map:'smith',target:'smith-shop',type:'buy',name:'첫 번째 무기',gold:10,xp:20,outcome:'준비 완료! 마을 동쪽 숲으로 가자.'},
 {id:'sun',chapter:1,title:'숲의 슬라임 2마리 물리치기',map:'forest',target:'slime-a',type:'kills',needs:['slime-a','slime-b'],name:'햇살 조각',gold:30,xp:35,star:'sun',outcome:'슬라임이 숨긴 햇살 별을 찾았다!'},
 {id:'report',chapter:1,title:'Mia에게 햇살 별 보여주기',map:'village',target:'mia',type:'talk',name:'바다로 가는 길',context:'첫 번째 별이 돌아왔네! 나머지는 바다와 산에 있어.',lines:[line('Did you find it?','찾았니?','Here it is.','여기 있어.'),line('Lucy needs your help.','Lucy에게 도움이 필요해.','I will help her.','내가 도와줄게.')],gold:25,xp:25,unlock:'coast',outcome:'바다 마을로 가는 배가 열렸다.'},
 {id:'lucy',chapter:2,title:'파도 여관의 Lucy 만나기',map:'inn',target:'lucy',type:'talk',name:'파도에 숨은 별',context:'해변의 몬스터들이 바다 별을 가져갔어. 밤바다가 어두워졌어.',lines:[line('Please find our star.','우리 별을 찾아 줘.','Where should I go?','어디로 가면 될까?'),line('Go to the beach.','해변으로 가.','I will be back.','다시 돌아올게.')],gold:15,xp:20,outcome:'해변의 게와 물방울 정령을 찾아가자.'},
 {id:'sea',chapter:2,title:'해변의 몬스터 2마리 물리치기',map:'coast',target:'crab',type:'kills',needs:['crab','water'],name:'바다의 약속',gold:40,xp:45,star:'sea',outcome:'파도 속에서 바다 별이 빛난다!'},
 {id:'sea-report',chapter:2,title:'Lucy에게 바다 별 돌려주기',map:'inn',target:'lucy',type:'talk',name:'산으로 가는 표',context:'바다에 불빛이 돌아왔어. 마지막 별은 산 위 유적에 있어.',lines:[line('Thank you for helping us.','우리를 도와줘서 고마워.','You are welcome.','천만에.'),line('Here is your ticket.','여기 네 표야.','To the mountain, please.','산으로 부탁해.')],gold:35,xp:30,unlock:'mountain',outcome:'산들 마을로 가는 길이 열렸다.'},
 {id:'amy',chapter:3,title:'산장에 있는 Amy 만나기',map:'lodge',target:'amy',type:'talk',name:'잠든 수호자',context:'유적의 수호자가 마지막 별을 지키고 있어. 저 상자에 문을 여는 열쇠가 있어.',lines:[line('Are you ready for this?','준비됐니?','Yes, I am ready.','응, 준비됐어.')],gold:10,xp:20,outcome:'산장 상자에서 유적 열쇠를 꺼내자.'},
 {id:'key',chapter:3,title:'산장 상자에서 열쇠 찾기',map:'lodge',target:'key-chest',type:'interact',name:'유적의 열쇠',gold:0,xp:15,outcome:'오래된 열쇠를 얻었다. 유적으로 가자.'},
 {id:'guardian',chapter:3,title:'별빛 유적의 수호자 물리치기',map:'ruins',target:'guardian',type:'kills',needs:['guardian'],name:'마지막 별빛',gold:90,xp:80,star:'moon',outcome:'세 개의 별이 모두 모였다. 고향으로 돌아가자!'},
 {id:'beacon',chapter:4,title:'햇살 마을의 별빛 제단 밝히기',map:'village',target:'beacon',type:'interact',name:'별빛의 귀환',gold:120,xp:80,outcome:'마을에 빛과 음악이 돌아왔다!',festival:true},
 {id:'finale',chapter:4,title:'Mia와 축제 시작하기',map:'village',target:'mia',type:'talk',name:'우리의 첫 번째 모험',context:'네가 건넨 말들이 세상을 다시 밝혔어. 이제 축제를 시작하자!',lines:[line('You saved our festival!','네가 우리 축제를 구했어!','We did it together!','우리가 함께 해냈어!')],gold:80,xp:50,outcome:'축제의 영웅! 새 의상이 상점에 도착했다.'}
];
// Every challenge has one contextually correct answer. Answers are taught before recall.
const rawQuestions=[
 [1,'인사를 건네세요.','Hello!','Hi!','안녕!','Good night.|Sorry.'],
 [1,'물을 부탁하세요.','What would you like?','Water, please.','물 주세요.','One ticket, please.|Goodbye.'],
 [1,'도와준 사람에게 감사하세요.','Here you are.','Thank you.','고마워.','I am hungry.|Good night.'],
 [1,'만났을 때 이름을 말하세요.','What is your name?','I am Mina.','나는 미나야.','I am fine.|Water, please.'],
 [1,'괜찮다고 답하세요.','How are you?','I am fine.','나는 괜찮아.','This one, please.|Goodbye.'],
 [1,'작별 인사를 하세요.','See you later!','Goodbye!','잘 가!','Water, please.|I am hungry.'],
 [2,'도와주겠다고 말하세요.','Can you help me?','I can help.','내가 도와줄게.','I am hungry.|One ticket, please.'],
 [2,'표 한 장을 부탁하세요.','How many tickets?','One ticket, please.','표 한 장 주세요.','Water, please.|I am fine.'],
 [2,'준비됐다고 답하세요.','Are you ready?','Yes, I am.','응, 준비됐어.','No, thank you.|I am lost.'],
 [2,'선택한 물건을 가리키세요.','Which one?','This one, please.','이걸로 주세요.','See you later.|I am fine.'],
 [2,'물건을 건네세요.','May I have it?','Here you are.','여기 있어.','Good morning.|I am hungry.'],
 [2,'길을 잃었다고 말하세요.','What is wrong?','I am lost.','길을 잃었어.','I am ready.|Thank you.'],
 [3,'공원 위치를 물으세요.','Can I help you?','Where is the park?','공원이 어디에 있나요?','I like this park.|The park is nice.'],
 [3,'다시 돌아오겠다고 약속하세요.','Will you come back?','I will be back.','다시 돌아올게.','I cannot come back.|I need some water.'],
 [3,'도움이 필요하다고 말하세요.','What do you need?','I need your help.','네 도움이 필요해.','I have a ticket.|I like the sea.'],
 [3,'가격을 물어보세요.','Do you like this sword?','How much is it?','얼마인가요?','It is very nice.|I am from Korea.'],
 [3,'산으로 가고 싶다고 말하세요.','Where are you going?','To the mountain, please.','산으로 부탁해요.','I am very tired.|This is my ticket.'],
 [3,'가방을 찾고 있다고 말하세요.','What are you looking for?','I need my bag.','내 가방이 필요해요.','I like your bag.|This is your bag.'],
 [4,'물을 마셔도 되는지 물으세요.','You look thirsty.','Can I have some water?','물 좀 마실 수 있을까요?','I do not want water.|I have a train ticket.'],
 [4,'그곳에 가는 길을 물으세요.','The station is nearby.','How do I get there?','거기에 어떻게 가나요?','I was there yesterday.|I like this town.'],
 [4,'다른 사람을 돕겠다고 말하세요.','Lucy lost her compass.','I will help her find it.','그녀가 찾는 걸 도와줄게.','I do not need it.|She has a new room.'],
 [4,'한 번 더 말해 달라고 하세요.','The path is over there.','Could you say that again?','다시 말해 주시겠어요?','I know the way.|The food is very good.'],
 [4,'여기서 기다리겠다고 말하세요.','Please wait for me.','I will wait for you here.','여기서 널 기다릴게.','I am leaving right now.|You have a nice hat.'],
 [4,'역에 가는지 물으세요.','This bus leaves soon.','Does this go to the station?','이것은 역에 가나요?','I like this blue bus.|It is a sunny day.'],
 [5,'창가 자리를 부탁하세요.','Where would you like to sit?','Could I sit by the window?','창가에 앉아도 될까요?','I would like some water.|The window is very clean.'],
 [5,'방을 하룻밤 예약하세요.','How long will you stay?','I would like a room for one night.','하룻밤 묵을 방을 원해요.','I need two train tickets.|I have lost my phone.'],
 [5,'매운 음식을 못 먹는다고 말하세요.','Would you like the spicy soup?','I cannot eat very spicy food.','아주 매운 음식은 먹지 못해요.','I love very spicy food.|The station is far away.'],
 [5,'방금 열쇠를 찾았다고 말하세요.','Did you find the key?','Yes, I found it near the river.','응, 강 근처에서 찾았어.','No, I cannot find it.|I am looking for the shop.'],
 [5,'여권을 잃어버렸다고 말하세요.','Why do you need help?','I think I have lost my passport.','여권을 잃어버린 것 같아요.','I have two tickets here.|I enjoyed my lunch today.'],
 [5,'함께 가자고 제안하세요.','I am going to the market.','Would you like to go together?','함께 가고 싶나요?','I was there last year.|I do not like this food.'],
 [6,'카드 결제가 되는지 물으세요.','That will be twenty dollars.','Can I pay for this by card?','이것을 카드로 결제해도 될까요?','I bought this card yesterday.|I want to go for a walk.'],
 [6,'시간이 부족해서 서둘러야 한다고 말하세요.','Our train leaves in five minutes.','We should hurry or we will miss it.','놓칠 수 있으니 서둘러야 해요.','We have plenty of time to rest.|I want to buy a new shirt.'],
 [6,'천천히 말해 달라고 부탁하세요.','Do you understand the directions?','Could you speak a little more slowly?','조금 더 천천히 말해 주시겠어요?','Please speak as fast as you can.|I really enjoyed the concert.'],
 [6,'방금 받은 음식이 차갑다고 말하세요.','Is everything all right with your meal?','Excuse me, my soup is a little cold.','실례지만 제 수프가 조금 차가워요.','The soup is too hot to eat.|I have a reservation for tomorrow.'],
 [6,'다음 버스 시간을 물으세요.','You just missed the bus.','Do you know when the next bus arrives?','다음 버스가 언제 오는지 아시나요?','I know where you bought this bag.|I would like a room with a view.'],
 [6,'사진을 찍어 달라고 부탁하세요.','This is a beautiful view.','Could you take a picture of us here?','여기서 저희 사진을 찍어 주시겠어요?','I do not want any pictures today.|We need to return these tickets.'],
 [7,'예약 이름을 알려주세요.','Do you have a reservation?','Yes, I booked a table under the name Mina.','네, 미나라는 이름으로 테이블을 예약했어요.','No, I only want to ask the price.|I lost my suitcase at the station.'],
 [7,'알레르기를 설명하세요.','Would you like some nuts?','No, thank you. I am allergic to nuts.','괜찮아요. 저는 견과류 알레르기가 있어요.','Yes, I would love a large bowl.|I am planning to stay for a week.'],
 [7,'표 날짜를 바꾸고 싶다고 말하세요.','How can I help with your ticket?','I would like to change it to tomorrow.','내일로 바꾸고 싶어요.','I want to buy a bottle of water.|The weather was beautiful yesterday.'],
 [7,'도움을 받아 안심했다고 말하세요.','Your bag is safe at the front desk.','That is a relief. Thank you for your help.','다행이에요. 도와주셔서 고마워요.','I am sorry but I cannot help you.|I do not want to visit that museum.'],
 [7,'비 때문에 실내에 있자고 제안하세요.','It is raining very hard outside.','Maybe we should stay inside until it stops.','비가 그칠 때까지 안에 있는 게 좋겠어요.','We should leave our coats at home.|I am looking for a cheaper ticket.'],
 [7,'조식 포함 여부를 물으세요.','Here is your room key.','Could you tell me if breakfast is included?','조식이 포함되는지 알려 주시겠어요?','I had a wonderful breakfast yesterday.|I need to find the nearest post office.'],
 [8,'길 안내를 확인하세요.','Turn left after the bridge.','So I cross the bridge and then turn left?','그러면 다리를 건넌 다음 왼쪽으로 가나요?','I should turn right before the bridge.|I would like to exchange this jacket.'],
 [8,'객실 문제를 정중히 설명하세요.','Is there a problem with your room?','The air conditioner is not working. Could someone check it?','에어컨이 작동하지 않아요. 확인해 주실 수 있나요?','Everything is perfect and I need nothing.|I would like to book a boat tour.'],
 [8,'환승 위치를 물으세요.','This train does not go directly to the airport.','Where should I change trains to get to the airport?','공항에 가려면 어디에서 환승해야 하나요?','I already arrived at the airport yesterday.|I would like to order a cup of tea.'],
 [8,'분실물의 생김새를 설명하세요.','What does your missing bag look like?','It is a small brown bag with a blue ribbon.','파란 리본이 달린 작은 갈색 가방이에요.','I think I left it near the cafe.|I bought it because it was very cheap.'],
 [8,'함께 해결하자고 말하세요.','I do not think I can do this alone.','You do not have to. We can figure it out together.','혼자 하지 않아도 돼. 함께 방법을 찾을 수 있어.','You should do everything by yourself.|I cannot remember the price of lunch.'],
 [8,'대체 일정을 물으세요.','The boat trip has been canceled today.','Is there another trip we could join tomorrow instead?','대신 내일 참여할 수 있는 다른 여행이 있나요?','I enjoyed the boat trip last summer.|The boat was bigger than I expected.'],
 [9,'일정을 바꾸는 이유와 새 시간을 말하세요.','Why would you like to change your booking?','My flight was delayed, so I would like to arrive tomorrow instead.','항공편이 지연되어 대신 내일 도착하고 싶어요.','I arrived early and have already checked in.|The room was very comfortable last night.'],
 [9,'예산 안에서 추천을 부탁하세요.','What kind of hotel are you looking for?','Could you recommend a quiet hotel that costs less than eighty dollars a night?','하룻밤에 80달러 미만인 조용한 호텔을 추천해 주시겠어요?','I booked the most expensive room in the city.|I have already found a hotel I like.'],
 [9,'서로 다른 의견을 듣고 타협안을 제안하세요.','I want to rest, but you want to explore.','How about resting for an hour and then exploring the town together?','한 시간 쉬었다가 함께 마을을 둘러보는 건 어때?','We must explore now and never take a break.|I have already packed my bag for tomorrow.'],
 [9,'주문과 다른 음식이 왔다고 설명하세요.','Is there anything wrong with your order?','I ordered the vegetable soup, but I think this one has chicken in it.','채소 수프를 주문했는데 이것에는 닭고기가 든 것 같아요.','This is exactly what I ordered and it tastes great.|I would like to thank the chef for the meal.'],
 [9,'돌아가는 길에 들를 곳을 제안하세요.','We should head back to the village soon.','Before we go home, could we stop at the shop to buy a gift?','집에 가기 전에 선물을 사러 상점에 들러도 될까요?','We have already arrived home with all our gifts.|I do not remember where I left my shoes.'],
 [9,'기차를 놓친 사람에게 다른 방법을 제안하세요.','I missed the last train to the coast.','If there are no more trains, we could check whether a bus is available.','기차가 더 없다면 버스가 있는지 알아볼 수 있어요.','You should wait for the train that has already left.|I took that train on my last holiday.'],
 [10,'숙소에 늦게 도착할 예정이라고 알려주세요.','What time do you expect to arrive?','Our train has been delayed, so we may arrive after midnight. Would that be all right?','기차가 지연되어 자정 이후에 도착할 수도 있어요. 괜찮을까요?','We arrived this morning and have already left the hotel.|We do not need a room because we are staying home.'],
 [10,'환불 대신 다른 날짜를 선택하고 싶다고 말하세요.','Would you prefer a refund for the canceled tour?','If possible, I would rather join the tour on another day than get a refund.','가능하다면 환불보다 다른 날 투어에 참여하고 싶어요.','Please cancel everything and give me all my money back.|I enjoyed the tour and do not want to change anything.'],
 [10,'실수를 인정하고 해결책을 물으세요.','Your ticket is for yesterday, not today.','I am sorry, I must have chosen the wrong date. Is there any way to change it?','죄송해요. 날짜를 잘못 선택했나 봐요. 변경할 방법이 있을까요?','I chose the correct date and do not want any help.|Thank you for showing me where the restaurant is.'],
 [10,'다른 사람의 걱정을 이해하고 함께하겠다고 말하세요.','I am nervous about speaking English on my trip.','It is okay to make mistakes. We can practice together, and I will help you when you need it.','실수해도 괜찮아. 함께 연습하고 필요할 때 도와줄게.','You should never speak until you know every word perfectly.|I am too busy to listen to anything you say.'],
 [10,'조건이 맞으면 예약하겠다고 말하세요.','Would you like to book this room now?','If breakfast is included and we can check in early, I would be happy to book it.','조식이 포함되고 일찍 체크인할 수 있다면 예약하고 싶어요.','I have already canceled the booking and gone home.|The room was larger than I expected last year.'],
 [10,'여행을 마치며 배운 점을 이야기하세요.','What did you enjoy most about your adventure?','Meeting new people taught me that even a few kind words can make a big difference.','새 사람들을 만나며 따뜻한 말 몇 마디도 큰 변화를 만들 수 있다는 걸 배웠어.','I have not started my journey and I do not know where to go.|I need you to tell me the price of this ticket.']
];
const questions=rawQuestions.map((q,i)=>({id:'word-'+i,tier:q[0],cue:q[1],prompt:q[2],answer:q[3],meaning:q[4],wrong:q[5].split('|')}));
const monsters={
 'slime-a':{name:'이끼 슬라임',kind:'slime',map:'forest',x:9,y:10,hp:52,attack:11,xp:24,gold:22,color:'#83bb73'},
 'slime-b':{name:'꽃잎 슬라임',kind:'slime',map:'forest',x:17,y:7,hp:62,attack:12,xp:26,gold:24,color:'#d383a0'},
 'sprout':{name:'새싹 정령',kind:'sprout',map:'forest',x:15,y:16,hp:70,attack:12,xp:28,gold:24,color:'#65a88b'},
 'crab':{name:'산호 게',kind:'crab',map:'coast',x:19,y:15,hp:100,attack:15,xp:35,gold:30,color:'#df8872'},
 'water':{name:'물방울 정령',kind:'slime',map:'coast',x:10,y:19,hp:112,attack:16,xp:38,gold:32,color:'#6ab4d4'},
 'bat':{name:'달빛 박쥐',kind:'bat',map:'mountain',x:17,y:14,hp:135,attack:18,xp:42,gold:36,color:'#a191c4'},
 'guardian':{name:'잠든 별의 수호자',kind:'guardian',map:'ruins',x:11,y:7,hp:230,attack:21,xp:85,gold:75,color:'#b3a2d2',boss:true}
};
module.exports={items,quests,questions,monsters};
