import L from './logic.cjs';
import M from './maps.cjs';
import {World} from './world.js';
import {artReady,sprite} from './sprites.js';
import {hero,monster,tree,star,rect,ellipse} from './art.js';
const $=id=>document.getElementById(id),{items,quests,questions,monsters}=L,{maps}=M;
let key='english_starword_rpg_v1',legacyKey='english_travel_village_v2';try{const kid=localStorage.getItem('family_todos_selected_kid_id');if(kid){key+=':'+kid;legacyKey+=':'+kid}}catch{}
let state;try{state=L.sanitize(JSON.parse(localStorage.getItem(key)||'null'),JSON.parse(localStorage.getItem(legacyKey)||'null'))}catch{state=L.fresh()}
let world,started=false,modal='welcome',dialog=null,battle=null,battlePhase='study',lastHit=null,hitTime=0,shopSlot='weapon',bagTab='gear',navigation=null,changingMap=false,toastTimer,rec=null,speechSerial=0,resultAction=null,focusBefore=null,battleFrame=0;
const outfit=()=>items.find(i=>i.id===state.outfit),weapon=()=>items.find(i=>i.id===state.weapon),playerName=()=>state.avatar==='jun'?'준':'미나';
function save(){try{localStorage.setItem(key,JSON.stringify(state))}catch{toast('이번 진행을 저장하지 못했어요. 저장 공간을 확인해 주세요.')}}
function toast(text){clearTimeout(toastTimer);$('toast').textContent=text;$('toast').hidden=false;toastTimer=setTimeout(()=>$('toast').hidden=true,3000)}
function stopAudio(){speechSerial++;if(rec){try{rec.abort()}catch{}rec=null}try{speechSynthesis.cancel()}catch{}}
function say(text){if(!state.sound||!window.speechSynthesis)return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.78;u.voice=speechSynthesis.getVoices().find(v=>/en-US/.test(v.lang))||null;speechSynthesis.speak(u)}catch{}}
let battleLayout=null;
function layoutBattle(){if(!battle||modal!=='battle')return;const w=innerWidth,h=innerHeight,wide=w>=650&&h<560,mobile=w<650,card=document.querySelector('.battle-card'),status=document.querySelector('.fighter-status'),floor=wide?Infinity:card.getBoundingClientRect().top-status.offsetHeight-22,hy=Math.min(h*(wide?.64:mobile?.435:.46),floor),my=Math.min(h*(wide?.58:mobile?.405:.42),hy-20),headBottom=document.querySelector('.battle-hud>div').getBoundingClientRect().bottom;
 battleLayout={hy,my,scale:wide?1.8:mobile?Math.min(2.05,Math.max(1.3,(hy-headBottom-12)/64)):2.75};status.style.top=wide?'':`${hy+10}px`;status.style.bottom=wide?'':'auto';}
let audioCtx;function chime(win=false){if(!state.sound)return;try{audioCtx||=new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume().catch(()=>{});[0,1,2].forEach((i)=>{const o=audioCtx.createOscillator(),g=audioCtx.createGain(),t=audioCtx.currentTime+i*.08;o.type='sine';o.frequency.value=win?[523,659,784][i]:[440,554,659][i];g.gain.setValueAtTime(.035,t);g.gain.exponentialRampToValueAtTime(.001,t+.18);o.connect(g);g.connect(audioCtx.destination);o.start(t);o.stop(t+.2)})}catch{}}
function setModal(id){if(id&&!modal)focusBefore=document.activeElement;modal=id;for(const name of ['welcome','dialog','shop','bag','battle','result'])$(name).hidden=name!==id;document.body.classList.toggle('is-modal',!!id);document.body.dataset.modal=id||'';for(const node of [document.querySelector('.hud'),$('missionButton'),$('markers'),$('world')])node.inert=!!id;world?.setEnabled(started&&!id&&!changingMap);if(id)requestAnimationFrame(()=>$(id).querySelector('button:not(:disabled)')?.focus());else if(focusBefore?.isConnected)focusBefore.focus({preventScroll:true});}
function close(){stopAudio();dialog=null;navigation=null;setModal(null);world.canvas.focus({preventScroll:true})}
function drawHero(canvas,override={},scale=1.6){const c=canvas.getContext('2d');c.clearRect(0,0,canvas.width,canvas.height);c.imageSmoothingEnabled=true;hero(c,canvas.width/2,canvas.height-10,{outfit:outfit(),weapon:weapon(),avatar:state.avatar,scale,...override})}
function update(){const st=L.stats(state),q=L.currentQuest(state);$('heroLevel').textContent=`Lv.${st.level} ${playerName()}`;$('gold').textContent=state.gold;$('hudHp').style.width=`${state.hp/st.maxHp*100}%`;$('heroButton').setAttribute('aria-label',`레벨 ${st.level} ${playerName()}, 체력 ${state.hp}/${st.maxHp}, 장비 열기`);$('missionText').textContent=q?q.title:'축제의 영웅 · 자유롭게 모험하기';$('chapter').textContent=q?`CH.0${q.chapter}`:'CLEAR';$('missionButton').dataset.quest=q?.id||'complete';$('soundButton').textContent=state.sound?'♪':'♩';$('soundButton').setAttribute('aria-label',state.sound?'소리 끄기':'소리 켜기');$('soundButton').setAttribute('aria-pressed',String(state.sound));$('location').textContent=maps[state.map].name;drawHero($('portrait'),{weapon:null},.82);updateMarkersGoal();}
function questTarget(){const q=L.currentQuest(state);if(!q)return null;return {map:q.map,id:q.type==='kills'?(q.needs.find(id=>!state.kills.includes(id))||q.needs.find(id=>!world?.defeated.has(id))||q.target):q.target}}
function firstDoor(from,to){if(from===to)return null;const queue=[{id:from,first:null}],seen=new Set([from]);while(queue.length){const a=queue.shift();for(const e of maps[a.id].entities.filter(e=>e.type==='door')){if(!L.canEnter(state,e.to)||seen.has(e.to))continue;const first=a.first||e; if(e.to===to)return first;seen.add(e.to);queue.push({id:e.to,first})}}return null;}
function guideTarget(){const target=questTarget();if(!target)return null;return state.map===target.map?target.id:firstDoor(state.map,target.map)?.id;}
function updateMarkersGoal(){if(!world)return;const goal=guideTarget();for(const b of $('markers').children){b.classList.toggle('goal',b.dataset.id===goal);const e=world.map.entities.find(x=>x.id===b.dataset.id);b.querySelector('.symbol').textContent=b.dataset.id===goal?'!':e?.icon||'…';b.setAttribute('aria-label',`${e?.name}${b.dataset.id===goal?' · 현재 미션':''}`)}}
function markers(map){$('markers').replaceChildren();for(const e of map.entities){const b=document.createElement('button');b.className='marker'+(e.type==='monster'?' monster':'');b.dataset.id=e.id;b.hidden=true;const icon=document.createElement('span'),name=document.createElement('span');icon.className='symbol';icon.textContent=e.icon;name.textContent=e.name;b.append(icon,name);b.onclick=()=>{navigation=null;if(!world.walkToEntity(e.id))toast('길 가까이에서 다시 이동해 주세요.')};$('markers').append(b)}updateMarkersGoal();}
function goMission(){const target=questTarget();if(!target){bagTab='journal';openBag();return}stopAudio();setModal(null);navigation=target;followNavigation();}
function followNavigation(){if(!navigation||changingMap)return;const e=state.map===navigation.map?world.map.entities.find(e=>e.id===navigation.id):firstDoor(state.map,navigation.map);if(!e){navigation=null;toast('이야기를 진행하면 길이 열려요.');return}if(!world.walkToEntity(e.id)){navigation=null;toast('길을 눌러 조금 이동한 뒤 다시 눌러 주세요.')}}
async function changeMap(e){if(changingMap)return;if(!L.canEnter(state,e.to)){toast(e.to==='ruins'?'Amy를 만나 유적의 열쇠를 찾아요.':'현재 퀘스트를 마치면 이 길이 열려요.');navigation=null;return}changingMap=true;world.setEnabled(false);$('transitionName').textContent=maps[e.to].name;$('transition').hidden=false;stopAudio();await new Promise(resolve=>setTimeout(resolve,260));state.map=e.to;world.setMap(e.to,e.spawn);save();update();$('transition').hidden=true;changingMap=false;setModal(null);if(navigation)setTimeout(followNavigation,120)}
function interact(e){if(modal||changingMap)return;if(e.type==='door'){changeMap(e);return}navigation=null;
 if(e.type==='monster'){startBattle(e.id);return}
 if(e.type==='rest'){L.rest(state);save();update();chime();toast('푹 쉬었어요. 체력 완전 회복 ♥');return}
 if(e.type==='wardrobe'){bagTab='gear';openBag();return}
 if(e.role==='weapon'||e.role==='outfit'){openShop(e.role);return}
 if(e.type==='chest'){if(e.id==='forest-chest'){if(state.choices['forest-chest']){toast('상자가 비어 있어요.');return}state.choices['forest-chest']=true;L.reward(state,15,0);save();update();toast('보물 발견 · +15 G');chime();return}const reward=L.finishQuest(state,{type:'interact',target:e.id});if(reward){save();update();showQuestResult(reward)}else toast(state.key?'열쇠를 이미 챙겼어요.':'먼저 Amy에게 말을 걸어 보세요.');return}
 if(e.type==='beacon'){const reward=L.finishQuest(state,{type:'interact',target:e.id});if(reward){save();update();showQuestResult(reward)}else toast(state.festival?'네가 되찾은 별빛이 마을을 밝혀요.':`돌아온 별빛 ${state.stars.length}/3 · 모험을 이어가요.`);return}
 if(e.type==='npc')openDialog(e);
}
function openDialog(e){const q=L.currentQuest(state),isQuest=q?.type==='talk'&&q.target===e.id&&q.map===state.map;dialog={npc:e,quest:isQuest?q:null,index:0,lines:isQuest?q.lines:[{en:state.festival?'You did a great job!':'Good to see you!',ko:state.festival?'정말 잘했어!':'만나서 반가워!',answer:state.festival?'Thank you!':'Hello!',meaning:state.festival?'고마워!':'안녕!'}]};setModal('dialog');renderDialog();}
function renderDialog(){const l=dialog.lines[dialog.index];$('dialogName').textContent=dialog.npc.name;$('dialogPlayerName').textContent=playerName()+' · 나';$('dialogStep').textContent=`${dialog.index+1}/${dialog.lines.length}`;$('dialogContext').textContent=dialog.quest?.context||'';$('dialogContext').hidden=dialog.index>0||!dialog.quest?.context;$('dialogEnglish').textContent=l.en;$('dialogKorean').textContent=l.ko;$('dialogAnswer').textContent=l.answer;$('dialogMeaning').textContent=l.meaning;$('dialogNext').textContent=dialog.index===dialog.lines.length-1?'대답하기 ✓':'대답하기 ›';$('dialogFeedback').hidden=true;$('dialog').dataset.quest=dialog.quest?.id||'ambient';$('dialog').dataset.line=dialog.index;}
function nextDialog(){if(!dialog)return;stopAudio();if(dialog.index<dialog.lines.length-1){dialog.index++;renderDialog();return}const d=dialog;dialog=null;const reward=d.quest?L.finishQuest(state,{type:'talk',target:d.npc.id,quest:d.quest.id}):null;save();update();if(reward)showQuestResult(reward);else setModal(null)}
function speakDialog(){const API=window.SpeechRecognition||window.webkitSpeechRecognition;if(!API){$('dialogFeedback').textContent='마이크 미지원 · 대답하기를 눌러요.';$('dialogFeedback').hidden=false;return}if(!dialog)return;stopAudio();const serial=speechSerial,answer=dialog.lines[dialog.index].answer;try{rec=new API();rec.lang='en-US';rec.maxAlternatives=3;rec.onstart=()=>{if(serial!==speechSerial||!dialog)return;$('dialogFeedback').textContent='듣고 있어요…';$('dialogFeedback').hidden=false};rec.onresult=e=>{if(serial!==speechSerial||!dialog)return;const norm=s=>s.toLowerCase().replace(/[^a-z0-9]/g,'');if(Array.from(e.results[0]).some(r=>norm(r.transcript)===norm(answer))){nextDialog()}else{$('dialogFeedback').textContent='보이는 문장을 한 번 더 말해요.';$('dialogFeedback').hidden=false}};rec.onerror=()=>{if(serial!==speechSerial)return;$('dialogFeedback').textContent='마이크를 사용할 수 없어요. 대답하기로 계속해요.';$('dialogFeedback').hidden=false};rec.start()}catch{$('dialogFeedback').textContent='대답하기로 계속할 수 있어요.';$('dialogFeedback').hidden=false}}
function showResult({title,copy,gold=0,xp=0,levelUp=false,icon='✦',kicker='QUEST COMPLETE',extra='',action}){setModal('result');$('resultTitle').textContent=title;$('resultCopy').textContent=copy||'';$('resultCopy').hidden=!copy;$('resultIcon').textContent=icon;$('resultKicker').textContent=({'QUEST COMPLETE':'퀘스트 완료','QUEST & BATTLE COMPLETE':'퀘스트 완료','VICTORY':'전투 승리','A NEW TRY':'다시 도전'})[kicker]||kicker;$('resultRewards').replaceChildren();for(const label of [gold?`◈ +${gold} G`:null,xp?`+${xp} XP`:null,levelUp?`레벨 업 · Lv.${L.level(state)}`:null,extra||null].filter(Boolean)){const pill=document.createElement('span');pill.className=label.startsWith('◈')?'reward-gold':label.includes(' XP')?'reward-xp':'reward-extra';pill.textContent=label;$('resultRewards').append(pill)}resultAction=action||(()=>setModal(null));$('resultRewards').hidden=!$('resultRewards').children.length;$('resultNext').textContent='모험 계속 ›';chime(true);}
function showQuestResult(r){showResult({title:r.quest.name,copy:r.quest.outcome,...r,extra:r.quest.star?'✦ 별빛 획득':r.quest.id==='finale'?'축제의 영웅 칭호':r.quest.id==='key'?'⚿ 유적 열쇠':''});}
function openShop(slot){shopSlot=slot;setModal('shop');renderShop();}
function renderShop(){const st=L.stats(state);$('shopTitle').textContent=shopSlot==='weapon'?'Ben의 무기점':'Ella의 의상실';$('shopGold').textContent=state.gold;$('previewName').textContent=shopSlot==='weapon'?weapon().name:outfit().name;$('previewStats').textContent=`공격 ${st.attack} · 방어 ${st.defense}`;drawHero($('shopHero'),{},1.85);$('shopItems').replaceChildren();for(const item of items.filter(i=>i.slot===shopSlot&&i.price>0)){const owned=state.owned.includes(item.id),equipped=state[item.slot]===item.id,locked=item.festival&&!state.festival,row=document.createElement('div');row.className='shop-item'+(equipped?' selected':'');const cv=document.createElement('canvas');cv.width=70;cv.height=80;drawHero(cv,{[item.slot]:item},1.05);const copy=document.createElement('div'),name=document.createElement('strong'),desc=document.createElement('small'),button=document.createElement('button');name.textContent=item.name;desc.textContent=locked?'축제 복원 후 해금':item.desc;copy.append(name,desc);button.textContent=equipped?'장착 중':owned?'장착':locked?'잠김':`${item.price} G`;button.disabled=equipped||locked||(!owned&&state.gold<item.price);button.className=equipped?'equipped':'';button.setAttribute('aria-label',`${item.name} ${equipped?'장착 중':owned?'장착':locked?'잠김':`${item.price} 골드 구매`}`);button.onclick=()=>{if(owned){L.equip(state,item.id);toast(`${item.name} 장착`)}else{const result=L.purchase(state,item.id,shopSlot);if(!result.ok){toast(result.reason);return}chime();toast(result.quest?`${item.name} 장착 · 퀘스트 완료 +${result.quest.gold} G, +${result.quest.xp} XP`:`${item.name} 구입 · 장착 완료`)}save();update();renderShop()};row.append(cv,copy,button);$('shopItems').append(row)}}
function openBag(){setModal('bag');renderBag();}
function el(tag,text,cls){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;if(cls)e.className=cls;return e}
function renderBag(){document.querySelectorAll('[data-tab]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tab===bagTab)));const box=$('bagContent');box.replaceChildren();if(bagTab==='gear'){const sheet=el('div',undefined,'character-sheet'),cv=el('canvas');cv.width=160;cv.height=190;drawHero(cv,{},2.3);const info=el('div'),st=L.stats(state);info.append(el('h3',playerName()),el('small',`Lv.${st.level} · ${state.step===quests.length?'축제의 영웅':'별빛 여행자'}`),el('small',`♥ ${state.hp} / ${st.maxHp}`),el('small',`공격 ${st.attack} · 방어 ${st.defense}`));const xp=el('div',undefined,'xp-track'),bar=el('i'),base=L.thresholds[st.level-1],next=L.thresholds[st.level];bar.style.width=next?`${(state.xp-base)/(next-base)*100}%`:'100%';xp.append(bar);info.append(xp,el('small',next?`${state.xp-base} / ${next-base} XP`:'최고 레벨'));sheet.append(cv,info);box.append(sheet);
 for(const slot of ['outfit','weapon']){box.append(el('p',slot==='outfit'?'나의 의상':'나의 무기','section-label'));const grid=el('div',undefined,'gear-grid');for(const i of items.filter(i=>i.slot===slot&&state.owned.includes(i.id))){const b=el('button'),c=el('canvas');c.width=75;c.height=85;drawHero(c,{[slot]:i},1.15);b.append(c,el('span',i.name));b.setAttribute('aria-pressed',String(state[slot]===i.id));b.setAttribute('aria-label',i.name+' 장착');b.onclick=()=>{L.equip(state,i.id);save();update();renderBag()};grid.append(b)}box.append(grid)}box.append(el('p','무기점과 의상실에서 새 장비를 살 수 있어요.','tiny'));}
 else if(bagTab==='journal'){const q=L.currentQuest(state),note=el('div',undefined,'quest-note');note.append(el('span',q?`CHAPTER 0${q.chapter}`:'ADVENTURE COMPLETE','eyebrow'),el('h3',q?.name||'축제의 영웅'),el('p',q?.title||'세 개의 별빛이 돌아왔어요. 새 장비와 더 어려운 영어 전투에 도전해요.'));if(q?.type==='kills')note.append(el('p',`${q.needs.filter(id=>state.kills.includes(id)).length} / ${q.needs.length}마리`));const go=el('button',q?'목적지로 이동 →':'계속 걷기 →','primary');go.onclick=q?goMission:close;note.append(go);box.append(note);const stars=el('div',undefined,'stars');['sun','sea','moon'].forEach((id,i)=>{const s=el('span','✦',state.stars.includes(id)?'on':'');s.append(el('small',['햇살 별','바다 별','달빛 별'][i]));stars.append(s)});box.append(stars);if(state.key)box.append(el('p','⚿ 유적 열쇠','journal-line'));quests.slice(0,state.step).reverse().forEach(q=>box.append(el('div','✓ '+q.name,'journal-line')));}
 else if(bagTab==='words'){const list=questions.filter(q=>state.learned[q.id]||state.mistakes[q.id]).sort((a,b)=>(state.mistakes[b.id]||0)-(state.mistakes[a.id]||0));box.append(el('p',`${list.length}개 표현 · 틀렸던 문장부터 복습해요.`,'tiny'));if(!list.length)box.append(el('p','숲에서 몬스터와 첫 영어 전투를 해 보세요.','context'));for(const q of list){const row=el('div',undefined,'word-row'),copy=el('div');copy.append(el('b',q.answer),el('small',q.meaning),el('small',`정답 ${state.learned[q.id]||0}회 · 다시 연습 ${state.mistakes[q.id]||0}회`));const b=el('button','♪','listen');b.setAttribute('aria-label',q.answer+' 듣기');b.onclick=()=>say(q.answer);row.append(copy,b);box.append(row)}}
 else {for(const id of ['village','forest','coast','mountain','ruins','smith','tailor','home']){const b=el('button',undefined,'map-entry'),unlocked=L.canEnter(state,id);b.append(el('b',maps[id].name),el('small',state.map===id?'현재 위치':unlocked?'걸어가기 →':'잠김'));b.disabled=!unlocked||state.map===id;b.onclick=()=>{setModal(null);navigation={map:id,id:maps[id].entities.find(e=>e.type!=='door')?.id||maps[id].entities[0].id};followNavigation()};box.append(b)}box.append(el('p','방향키 / WASD 이동 · E 대화 · 장소를 눌러 이동','tiny'));}}
function startBattle(id){stopAudio();if(state.hp<=0){L.rest(state);save();update();toast('체력을 회복했어요. 다시 도전해요.')}battle=L.beginBattle(state,id);if(!battle)return;lastHit=null;setModal('battle');renderBattle();cancelAnimationFrame(battleFrame);battleFrame=requestAnimationFrame(drawBattle);}
function battleQuestion(){return questions.find(q=>q.id===battle?.question)}
function renderBattle(){if(!battle)return;$('fleeButton').disabled=false;battlePhase='study';const m=monsters[battle.id],q=battleQuestion(),st=L.stats(state);$('enemyName').textContent=m.name;$('enemyHp').style.width=`${battle.hp/battle.maxHp*100}%`;$('enemyHpText').textContent=`${battle.hp} / ${battle.maxHp}`;$('battleLevel').textContent=`Lv.${st.level} ${playerName()}`;$('battleHpText').textContent=`♥ ${state.hp} / ${st.maxHp}`;$('battleHp').style.width=`${state.hp/st.maxHp*100}%`;$('battleTier').textContent=`영어 ${q.tier}단계`;$('battleCombo').textContent=battle.combo>1?`${battle.combo} 연속`:m.boss?'BOSS':'';$('battleCue').textContent=q.cue;$('battlePrompt').textContent=q.prompt;$('studyAnswer').textContent=q.answer;$('studyMeaning').textContent=q.meaning;$('study').hidden=false;$('answerChoices').hidden=true;$('hintButton').hidden=true;$('battleFeedback').hidden=true;$('battleNext').hidden=true;$('battle').dataset.phase='study';$('battle').dataset.question=q.id;document.querySelector('.battle-card').scrollTop=0;layoutBattle();}
function recall(){if(!battle||battle.status!=='active')return;battlePhase='choose';$('study').hidden=true;$('answerChoices').hidden=false;$('hintButton').hidden=false;$('answerChoices').replaceChildren();const q=battleQuestion(),answers=[q.answer,...q.wrong];for(let i=answers.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[answers[i],answers[j]]=[answers[j],answers[i]]}for(const[a,index]of answers.map((a,i)=>[a,i])){const b=el('button');b.append(el('span',String(index+1)),document.createTextNode(a));b.dataset.answer=a;b.onclick=()=>attack(a);$('answerChoices').append(b)}$('battle').dataset.phase='choose';}
function attack(answer){if(battlePhase!=='choose'||!battle||battle.status!=='active')return;const r=L.answerBattle(state,battle,answer);if(!r)return;battlePhase='feedback';$('fleeButton').disabled=battle.status!=='active';lastHit=r;hitTime=performance.now();save();update();const q=battleQuestion();for(const b of $('answerChoices').children){b.disabled=true;if(b.dataset.answer===q.answer)b.classList.add('correct');else if(b.dataset.answer===answer)b.classList.add('wrong')}$('hintButton').hidden=true;$('enemyHp').style.width=`${battle.hp/battle.maxHp*100}%`;$('enemyHpText').textContent=`${battle.hp} / ${battle.maxHp}`;$('battleHpText').textContent=`♥ ${state.hp} / ${L.stats(state).maxHp}`;$('battleHp').style.width=`${state.hp/L.stats(state).maxHp*100}%`;$('battleFeedback').hidden=false;$('battleFeedback').replaceChildren();$('battleFeedback').append(el('strong',r.correct?`정답! ${r.damage} 데미지${battle.combo>1?` · ${battle.combo}연속!`:''}`:`체력 −${r.damage} · 이 답을 기억해요`));if(!r.correct)$('battleFeedback').append(el('span',`${q.answer} · ${q.meaning}`));$('battleNext').hidden=false;$('battleNext').textContent=r.won?'전리품 받기 →':r.lost?'마을에서 회복하기 →':'다음 공격 →';$('battle').dataset.phase=r.won?'won':r.lost?'lost':'feedback';$('battleLevel').textContent=`Lv.${L.level(state)} ${playerName()}`;requestAnimationFrame(()=>{if(modal==='battle'&&battlePhase==='feedback')$('battleNext').scrollIntoView({block:'nearest',behavior:'instant'})});if(r.correct)chime();}
function nextBattle(){if(!battle||battlePhase!=='feedback')return;stopAudio();if(battle.status==='won'){world.defeated.add(battle.id);$('markers').querySelector(`[data-id="${battle.id}"]`)?.remove();const r=lastHit,m=monsters[battle.id];cancelAnimationFrame(battleFrame);battle=null;showResult({title:r.quest?r.quest.quest.name:`${m.name} 격파!`,copy:r.quest?r.quest.quest.outcome:'',gold:r.gold+(r.quest?.gold||0),xp:r.xp+(r.quest?.xp||0),levelUp:r.levelUp||r.quest?.levelUp,kicker:r.quest?'QUEST & BATTLE COMPLETE':'VICTORY',extra:r.quest?.quest.star?'✦ 별빛 획득':''});return}if(battle.status==='lost'){cancelAnimationFrame(battleFrame);battle=null;L.rest(state);state.map='home';world.setMap('home');save();update();showResult({title:'잠깐 쉬어 가요',copy:'집에서 체력을 모두 회복했어요.',icon:'☾',kicker:'A NEW TRY'});return}L.advanceBattle(state,battle);renderBattle();}
function drawBattle(now){if(!battle||modal!=='battle')return;const canvas=$('battleCanvas'),dpr=Math.min(devicePixelRatio||1,2),w=innerWidth,h=innerHeight;if(canvas.width!==w*dpr||canvas.height!==h*dpr){canvas.width=w*dpr;canvas.height=h*dpr}const c=canvas.getContext('2d');c.setTransform(dpr,0,0,dpr,0,0);c.imageSmoothingEnabled=true;const t=now/1000,theme=maps[state.map].theme,m=monsters[battle.id],mobile=w<650,wide=w>h&&h<560,elapsed=(now-hitTime)/1000,hit=lastHit&&elapsed<.6;
 rect(c,theme==='ruins'?'#576359':theme==='beach'?'#c8b884':'#697b41',0,0,w,h);const arenaZoom=wide?1.7:mobile?1.9:2.1;c.save();c.translate(w*(wide?.25:.5)-world.camera.x*arenaZoom,h*.46-world.camera.y*arenaZoom);c.scale(arenaZoom,arenaZoom);c.drawImage(world.base,-world.baseOrigin.x,-world.baseOrigin.y,world.base.width/2,world.base.height/2);c.restore();
 if(theme!=='beach'&&theme!=='ruins'){c.save();c.translate(0,h*.40);c.scale(1.6,1.6);tree(c,0,0,1);c.restore();c.save();c.translate(w*(wide?.48:1),h*.29);c.scale(1.55,1.55);tree(c,0,0,0);c.restore()}if(theme==='ruins'){sprite(c,'monster','portal',w*(wide?.37:.77),h*.23,{height:h*.32,alpha:.6});sprite(c,'environment','lantern',w*.08,h*.36,{height:110});}
 const hx=w*(wide?.15:mobile?.23:.35),hy=battleLayout?.hy??h*.435,mx=w*(wide?.40:mobile?.77:.66),my=battleLayout?.my??h*.405,scale=battleLayout?.scale??2.05,lung=hit&&lastHit.correct?Math.sin(elapsed/.6*Math.PI)*28:0;
 hero(c,hx+lung,hy,{outfit:outfit(),weapon:weapon(),avatar:state.avatar,scale,direction:'right',attack:hit&&lastHit.correct?1:0});if(battle.hp>0||(hit&&elapsed<.4)){c.save();if(battle.hp===0)c.globalAlpha=Math.max(0,1-elapsed/.6);monster(c,mx+(hit&&lastHit.correct?Math.sin(elapsed*75)*4:0),my,m,t,scale*(m.boss?.8:1.05),hit&&lastHit.correct);c.restore()}
 if(hit){const xx=lastHit.correct?mx:hx,yy=lastHit.correct?my:hy;if(lastHit.correct){c.save();c.shadowColor='#fff5c1';c.shadowBlur=12;c.strokeStyle=weapon().style==='wand'?'#f3d085':'#f8f8d7';c.lineWidth=3;c.beginPath();c.moveTo(xx-40,yy-35+elapsed*35);c.lineTo(xx+35,yy-135+elapsed*35);c.stroke();for(let i=0;i<8;i++)star(c,xx+Math.cos(i)*elapsed*90,yy-50+Math.sin(i)*elapsed*90,'#ffe6ac',4);c.restore()}$('battleFloat').textContent=lastHit.correct?`−${lastHit.damage}`:`HP −${lastHit.damage}`;$('battleFloat').style.opacity=String(1-elapsed/.6)}else $('battleFloat').textContent='';
 const shade=c.createLinearGradient(0,h*.5,0,h);shade.addColorStop(0,'#2b271600');shade.addColorStop(1,'#2b271645');c.fillStyle=shade;c.fillRect(0,0,w,h);battleFrame=requestAnimationFrame(drawBattle);}

function bind(){document.querySelectorAll('[data-close]').forEach(b=>b.onclick=close);$('startButton').onclick=()=>{started=true;save();setModal(null);world.canvas.focus({preventScroll:true})};document.querySelectorAll('[data-avatar]').forEach(b=>b.onclick=()=>{state.avatar=b.dataset.avatar;document.querySelectorAll('[data-avatar]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));save();update()});$('soundButton').onclick=()=>{state.sound=!state.sound;if(!state.sound)stopAudio();save();update()};$('heroButton').onclick=()=>{bagTab='gear';openBag()};$('bagButton').onclick=openBag;$('missionButton').onclick=goMission;$('guideButton').onclick=goMission;$('interactButton').onclick=()=>{if(world.near)interact(world.near)};$('dialogNext').onclick=nextDialog;$('dialogNpcListen').onclick=()=>{if(dialog)say(dialog.lines[dialog.index].en)};$('dialogListen').onclick=()=>{if(dialog)say(dialog.lines[dialog.index].answer)};$('dialogMic').onclick=speakDialog;$('resultNext').onclick=()=>{const a=resultAction;resultAction=null;a?.();};document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{bagTab=b.dataset.tab;renderBag()});$('studyListen').onclick=()=>say(battleQuestion()?.answer);$('recallButton').onclick=recall;$('hintButton').onclick=()=>{if(battlePhase==='choose'){battlePhase='study';$('answerChoices').hidden=true;$('hintButton').hidden=true;$('study').hidden=false;$('battle').dataset.phase='study'}};$('battleNext').onclick=nextBattle;$('fleeButton').onclick=()=>{stopAudio();cancelAnimationFrame(battleFrame);battle=null;setModal(null);toast('물러났어요. 집과 여관에서 무료로 회복할 수 있어요.')};
 addEventListener('keydown',e=>{if(modal==='battle'&&battlePhase==='choose'&&['1','2','3'].includes(e.key)&&!e.repeat)$('answerChoices').children[Number(e.key)-1]?.click();if(e.key==='Escape'&&!['welcome','battle','result'].includes(modal))close();if(e.key==='Tab'&&modal){const dialog=$(modal),buttons=[...dialog.querySelectorAll('button:not(:disabled),input,summary')].filter(x=>x.getClientRects().length&&!x.closest('[hidden]'));const first=buttons[0],last=buttons.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}}});
 const pad=$('joystick'),knob=$('knob');let pointer=null;const reset=()=>{pointer=null;knob.style.transform='';world?.setJoystick(0,0)};const move=e=>{if(e.pointerId!==pointer)return;const r=pad.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,len=Math.hypot(dx,dy),s=len>23?23/len:1;knob.style.transform=`translate(${dx*s}px,${dy*s}px)`;world.setJoystick(dx*s/23,dy*s/23);navigation=null};pad.onpointerdown=e=>{if(!world.enabled)return;pointer=e.pointerId;pad.setPointerCapture(pointer);move(e)};pad.onpointermove=move;pad.onpointerup=reset;pad.onpointercancel=reset;addEventListener('blur',reset);document.addEventListener('visibilitychange',()=>{if(document.hidden){reset();stopAudio();save()}});
}
bind();world=new World($('world'),state,{onMap:map=>markers(map),onInteract:interact,onNear:e=>{$('interactButton').hidden=!e;if(e)$('interactButton').textContent=e.type==='monster'?`${e.name} · 전투 ⚔`:e.type==='door'?`${e.name} 입장 →`:e.type==='npc'?`${e.name} · 대화`:`${e.name}`;for(const b of $('markers').children)b.classList.toggle('near',b.dataset.id===e?.id)},onMarkers:points=>{for(const p of points){const b=$('markers').querySelector(`[data-id="${p.id}"]`);if(!b)continue;b.hidden=!p.visible;b.style.transform=`translate(${p.x}px,${p.y}px) translate(-50%,-100%)`}}});update();setModal('welcome');document.querySelectorAll('[data-avatar]').forEach(b=>{drawHero(b.querySelector('canvas'),{avatar:b.dataset.avatar},1.4);b.setAttribute('aria-pressed',String(b.dataset.avatar===state.avatar))});$('startButton').textContent=state.step||state.xp?'이어서 모험하기 →':'모험 시작 →';

$('startButton').disabled=true;$('startButton').textContent='마을 준비 중…';artReady.then(results=>{$('startButton').disabled=false;$('startButton').textContent=state.step||state.xp?'이어서 모험하기 →':'모험 시작 →';update();document.querySelectorAll('[data-avatar]').forEach(b=>drawHero(b.querySelector('canvas'),{avatar:b.dataset.avatar},1.25));if(modal==='shop')renderShop();if(modal==='bag')renderBag();if(results.some(ok=>!ok))toast('일부 그림을 불러오지 못했어요. 새로고침하면 다시 불러와요.');});

addEventListener('rpg-art-updated',()=>{update();document.querySelectorAll('[data-avatar]').forEach(b=>drawHero(b.querySelector('canvas'),{avatar:b.dataset.avatar},1.25));if(modal==='shop')renderShop();if(modal==='bag')renderBag();});

// Keep large text clear of fighters when choices wrap or the phone rotates.
new ResizeObserver(layoutBattle).observe(document.querySelector('.battle-card'));
addEventListener('resize',layoutBattle);
