const {monsters}=require('./data.cjs');
const door=(id,name,x,y,to,spawn,icon='↳')=>({id,name,x,y,type:'door',to,spawn,icon});
const npc=(id,name,x,y,color,role)=>({id,name,x,y,type:'npc',color,role,icon:'…'});
const building=(x,y,w,h,name,color)=>({x,y,w,h,name,color});
const maps={
 village:{name:'햇살 마을',subtitle:'시작의 마을',theme:'grass',w:27,h:25,spawn:[13,16],buildings:[building(3,4,6,5,'무기점','#716985'),building(18,5,6,5,'의상실','#b57b87'),building(4,15,5,4,'우리 집','#b27f64')],
  entities:[npc('mia','Mia',12,12,'#cf7690','festival'),door('smith-door','무기점',6,9,'smith',[8,11],'⚒'),door('tailor-door','의상실',21,10,'tailor',[8,11],'✂'),door('home-door','우리 집',6,19,'home',[8,11],'⌂'),door('forest-gate','속삭임 숲',25,13,'forest',[2,11],'→'),door('coast-gate','바다 마을',13,23,'coast',[3,12],'⚓'),{id:'beacon',name:'별빛 제단',x:13,y:7,type:'beacon',icon:'✦'}]},
 forest:{name:'속삭임 숲',subtitle:'햇살 별의 흔적',theme:'forest',w:25,h:23,spawn:[2,11],buildings:[],entities:[door('village-gate','햇살 마을',1,11,'village',[23,13],'←'),...['slime-a','slime-b','sprout'].map(id=>({id,...monsters[id],type:'monster',icon:'⚔'})),{id:'forest-chest',name:'낡은 보물상자',x:20,y:17,type:'chest',icon:'◇'}]},
 coast:{name:'바다 마을',subtitle:'파도의 약속',theme:'beach',w:27,h:25,spawn:[3,12],buildings:[building(4,4,7,5,'파도 여관','#658ca6')],entities:[door('inn-door','파도 여관',7,9,'inn',[8,11],'⌂'),door('home-ship','햇살 마을',2,12,'village',[13,21],'⚓'),door('mountain-gate','산들 마을',23,7,'mountain',[3,17],'↑'),...['crab','water'].map(id=>({id,...monsters[id],type:'monster',icon:'⚔'}))]},
 mountain:{name:'산들 마을',subtitle:'달빛이 머무는 산',theme:'mountain',w:25,h:24,spawn:[3,17],buildings:[building(4,5,7,5,'별바람 산장','#726783')],entities:[door('lodge-door','별바람 산장',7,10,'lodge',[8,11],'⌂'),door('coast-path','바다 마을',2,18,'coast',[21,8],'←'),door('ruin-gate','별빛 유적',19,5,'ruins',[11,15],'✦'),{id:'bat',...monsters.bat,type:'monster',icon:'⚔'},door('home-carriage','고향행 마차',9,21,'village',[13,21],'⌂')]},
 ruins:{name:'별빛 유적',subtitle:'마지막 별의 수호자',theme:'ruins',w:23,h:20,spawn:[11,15],buildings:[],entities:[door('ruin-exit','산들 마을',11,18,'mountain',[18,7],'↓'),{id:'guardian',...monsters.guardian,type:'monster',icon:'⚔'}]},
 smith:{name:'Ben의 무기점',theme:'interior',w:17,h:15,spawn:[8,11],shop:'weapon',entities:[npc('smith-shop','Ben',8,5,'#7087a2','weapon'),door('smith-exit','마을로',8,13,'village',[6,10],'↓')],furniture:[{x:2,y:3,w:3,h:3,kind:'weapons'},{x:12,y:3,w:3,h:3,kind:'forge'},{x:5,y:6,w:6,h:1,kind:'counter'}]},
 tailor:{name:'Ella의 의상실',theme:'interior',w:17,h:15,spawn:[8,11],shop:'outfit',entities:[npc('tailor-shop','Ella',8,5,'#c786a8','outfit'),door('tailor-exit','마을로',8,13,'village',[21,11],'↓')],furniture:[{x:2,y:3,w:3,h:3,kind:'clothes'},{x:12,y:3,w:3,h:3,kind:'clothes'},{x:5,y:6,w:6,h:1,kind:'counter'}]},
 home:{name:'나의 작은 집',theme:'interior',w:17,h:15,spawn:[8,11],entities:[{id:'home-bed',name:'쉬기 · 체력 회복',x:4,y:5,type:'rest',icon:'☾'},{id:'wardrobe',name:'옷장',x:12,y:4,type:'wardrobe',icon:'✂'},door('home-exit','마을로',8,13,'village',[6,20],'↓')],furniture:[{x:3,y:3,w:3,h:3,kind:'bed'},{x:11,y:3,w:3,h:2,kind:'wardrobe'},{x:7,y:7,w:3,h:2,kind:'table'}]},
 inn:{name:'파도 여관',theme:'interior',w:17,h:15,spawn:[8,11],entities:[npc('lucy','Lucy',8,5,'#609bbb','inn'),{id:'inn-bed',name:'쉬기 · 체력 회복',x:3,y:7,type:'rest',icon:'☾'},door('inn-exit','바다 마을로',8,13,'coast',[7,10],'↓')],furniture:[{x:2,y:3,w:3,h:3,kind:'bed'},{x:12,y:3,w:3,h:3,kind:'bed'},{x:6,y:6,w:5,h:1,kind:'counter'}]},
 lodge:{name:'별바람 산장',theme:'interior',w:17,h:15,spawn:[8,11],entities:[npc('amy','Amy',6,6,'#9782b4','lodge'),{id:'key-chest',name:'열쇠 상자',x:12,y:5,type:'chest',icon:'◇'},{id:'lodge-bed',name:'쉬기 · 체력 회복',x:3,y:6,type:'rest',icon:'☾'},door('lodge-exit','산들 마을로',8,13,'mountain',[7,11],'↓')],furniture:[{x:2,y:3,w:3,h:2,kind:'bed'},{x:7,y:8,w:3,h:2,kind:'table'}]}
};
function blocked(map,x,y){if(x<1||y<2||x>=map.w-1||y>=map.h-1)return true;if(map.theme==='interior'&&y<3)return true;return (map.buildings||[]).some(b=>x>=b.x&&x<b.x+b.w&&y>=b.y&&y<b.y+b.h)||(map.furniture||[]).some(b=>x>=b.x&&x<b.x+b.w&&y>=b.y&&y<b.y+b.h);}
// A* over tile centers. An interaction tile is selected next to solid furniture.
function route(map,start,end){let sx=Math.round(start.x),sy=Math.round(start.y),ex=Math.round(end.x),ey=Math.round(end.y);if(blocked(map,ex,ey))return[];let open=[{x:sx,y:sy,g:0,f:0}],closed=new Set(),best=new Map([[`${sx},${sy}`,0]]);while(open.length){open.sort((a,b)=>a.f-b.f);const n=open.shift(),key=`${n.x},${n.y}`;if(closed.has(key))continue;closed.add(key);if(n.x===ex&&n.y===ey){const out=[];let c=n;while(c.parent){out.unshift({x:c.x,y:c.y});c=c.parent;}return out;}for(const[dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]]){const x=n.x+dx,y=n.y+dy,k=`${x},${y}`,g=n.g+1;if(blocked(map,x,y)||g>=(best.get(k)??Infinity))continue;best.set(k,g);open.push({x,y,g,f:g+Math.abs(ex-x)+Math.abs(ey-y),parent:n});}}return[];}
function approach(map,entity,start){const spots=[{x:entity.x,y:entity.y+1},{x:entity.x-1,y:entity.y},{x:entity.x+1,y:entity.y},{x:entity.x,y:entity.y-1}].filter(p=>!blocked(map,p.x,p.y));const paths=spots.map(p=>({point:p,path:route(map,start,p)})).filter(o=>o.path.length||Math.hypot(start.x-o.point.x,start.y-o.point.y)<.7);paths.sort((a,b)=>a.path.length-b.path.length);return paths[0]||null;}
module.exports={maps,blocked,route,approach};
