import M from './maps.cjs';
import D from './data.cjs';
import I from './isometric.cjs';
import {hero,monster,tree,chest,rect,ellipse,star,weaponIcon} from './art.js';
import {sprite} from './sprites.js';
const {maps,blocked,route,approach}=M,{toIso,fromIso,screenMovement,screenDirection}=I,TILE=32;
const hash=(x,y)=>{const n=Math.sin(x*127.1+y*311.7)*43758.5453;return n-Math.floor(n)};
const palettes={grass:['#829948','#627637','#d6c18b'],forest:['#617c3b','#405b2c','#baa97b'],beach:['#cab887','#ae9768','#d5c493'],mountain:['#799079','#4d6a5f','#b4b0a0'],ruins:['#687675','#414e50','#acaa98'],interior:['#b18b5e','#735232','#b49571']};
const paths={village:[[11,6,4,19],[3,11,23,4],[5,8,3,14],[20,9,3,4]],forest:[[1,10,18,3],[14,6,3,13],[8,7,3,8]],coast:[[1,11,22,3],[6,8,3,13],[20,6,4,12]],mountain:[[1,16,19,3],[6,9,3,14],[17,5,4,13]],ruins:[[7,3,9,16]]};
function poly(c,points,color,line){c.beginPath();points.forEach((p,i)=>i?c.lineTo(p.x,p.y):c.moveTo(p.x,p.y));c.closePath();c.fillStyle=color;c.fill();if(line){c.strokeStyle=line;c.lineWidth=.7;c.stroke()}}
function box(c,x,y,w,d,h,colors=['#c5b187','#9b8059','#796847']){const p=[toIso(x,y),toIso(x+w,y),toIso(x+w,y+d),toIso(x,y+d)],top=p.map(p=>({x:p.x,y:p.y-h}));poly(c,[p[1],p[2],top[2],top[1]],colors[2],'#65553b');poly(c,[p[2],p[3],top[3],top[2]],colors[1],'#65553b');poly(c,top,colors[0],'#e4d6af');return {p,top};}
function texture(theme,stone,variation){const cv=document.createElement('canvas');cv.width=cv.height=64;const c=cv.getContext('2d'),p=palettes[theme];c.fillStyle=stone?p[2]:p[0];c.fillRect(0,0,64,64);
 if(stone){c.strokeStyle='#84714e';c.lineWidth=1.3;c.strokeRect(1,1,62,62);c.strokeStyle='#ede0b699';c.lineWidth=1;c.beginPath();c.moveTo(3,61);c.lineTo(3,3);c.lineTo(61,3);c.stroke();c.strokeStyle='#7b6f4d77';c.beginPath();c.moveTo(62,3);c.lineTo(62,62);c.lineTo(3,62);c.stroke();for(let stain=0;stain<9;stain++){const x=hash(stain,variation+3)*64,y=hash(stain,variation+62)*64,g=c.createRadialGradient(x,y,1,x,y,8+hash(stain,3)*14);g.addColorStop(0,stain%2?'#fff1c433':'#6a5c3927');g.addColorStop(1,'#b6a57b00');c.fillStyle=g;c.fillRect(2,2,60,60)}for(let i=0;i<230;i++){const x=hash(i,variation+11)*60+2,y=hash(i,variation+99)*60+2;c.fillStyle=i%3?'#fff0c838':'#564b3230';c.fillRect(x,y,1+hash(i,9)*4,1)}if(variation%3===1){c.strokeStyle='#7c704c3a';c.lineWidth=.6;c.beginPath();c.moveTo(2,21);c.lineTo(12,29);c.lineTo(13,37);c.lineTo(22,41);c.stroke()}if(theme==='interior'){for(let i=0;i<4;i++){c.fillStyle='#60482e66';c.fillRect(i*16,0,1,64);for(let j=0;j<8;j++){c.fillStyle='#ecc99930';c.fillRect(i*16+3,hash(j,i)*60,hash(j,variation)*9,1)}}}}
 else{for(let i=0;i<620;i++){const x=hash(i,variation+11)*64,y=hash(i,variation+91)*64;c.fillStyle=[p[1]+'70','#bed27666','#d6d6a844','#3b582d66'][i%4];c.fillRect(x,y,.65+hash(i,8),1+hash(i,1)*3)}if(theme==='beach'){c.fillStyle='#e5d4aa';for(let i=0;i<35;i++)c.fillRect(hash(i,3)*64,hash(i,5)*64,1,1)}}return cv;}
export class World{
 constructor(canvas,state,callbacks){this.canvas=canvas;this.c=canvas.getContext('2d');this.state=state;this.cb=callbacks;this.keys=new Set();this.joy={x:0,y:0};this.enabled=false;this.defeated=new Set();this.camera={x:0,y:0};this.path=[];this.direction='down';this.time=0;this.moving=false;
  this.resize=()=>{this.w=innerWidth;this.h=innerHeight;this.dpr=Math.min(devicePixelRatio||1,2);canvas.width=this.w*this.dpr;canvas.height=this.h*this.dpr;this.zoom=this.w<600?1.13:1.2;};this.resize();addEventListener('resize',this.resize);this.setMap(state.map);this.bind();this.last=performance.now();requestAnimationFrame(t=>this.frame(t));}
 setMap(id,spawn){this.map=maps[id]||maps.village;this.id=id;this.player={x:(spawn||this.map.spawn)[0],y:(spawn||this.map.spawn)[1]};this.camera=toIso(this.player.x,this.player.y);this.path=[];this.target=null;this.near=null;this.defeated.clear();this.buildBase();this.cb.onMap?.(this.map,id);}
 setEnabled(value){this.enabled=value;if(!value){this.keys.clear();this.joy={x:0,y:0};this.path=[];this.target=null;this.moving=false}}
 interaction(e){if((this.map.shop&&e.type==='npc')||e.id==='lucy')return{x:e.x,y:e.y+3};if(e.id==='home-bed')return{x:4,y:6};if(e.id==='wardrobe')return{x:12,y:5};return{x:e.x,y:e.y}}
 distance(e){const p=this.interaction(e);return Math.hypot(this.player.x-p.x,this.player.y-p.y)}
 walkToEntity(id){const e=this.map.entities.find(e=>e.id===id);if(!e||this.defeated.has(id))return false;if(this.distance(e)<1.75){this.cb.onInteract(e);return true}const p=this.interaction(e),a=approach(this.map,{...e,x:p.x,y:p.y},this.player);if(!a)return false;this.path=a.path;this.target=e;return true;}
 setJoystick(x,y){this.joy={x,y};if(Math.hypot(x,y)>.1){this.path=[];this.target=null}}
 bind(){addEventListener('keydown',e=>{if(!this.enabled||/INPUT|TEXTAREA/.test(e.target.tagName))return;const key=e.key.toLowerCase();if(['arrowup','arrowdown','arrowleft','arrowright','w','a','s','d','e',' '].includes(key))e.preventDefault();if((key==='e'||key===' ')&&!e.repeat&&this.near){this.cb.onInteract(this.near);return}this.keys.add(key)});addEventListener('keyup',e=>this.keys.delete(e.key.toLowerCase()));addEventListener('blur',()=>{this.keys.clear();this.setJoystick(0,0)});
  this.canvas.addEventListener('pointerdown',e=>{if(!this.enabled)return;const hits=this.map.entities.filter(en=>!this.defeated.has(en.id)).map(en=>{const p=this.project(en.x,en.y);return{en,d:Math.hypot(e.clientX-p.x,e.clientY-(p.y-(en.type==='npc'?32:18)*this.zoom))/this.zoom}}).sort((a,b)=>a.d-b.d);if(hits[0]?.d<26){this.walkToEntity(hits[0].en.id);return}this.path=route(this.map,this.player,this.unproject(e.clientX,e.clientY));this.target=null});}
 project(x,y){const p=toIso(x,y);return{x:(p.x-this.camera.x)*this.zoom+this.w/2,y:(p.y-this.camera.y)*this.zoom+this.h*.54}}
 unproject(x,y){return fromIso(this.camera.x+(x-this.w/2)/this.zoom,this.camera.y+(y-this.h*.54)/this.zoom)}
 onPath(x,y){return this.map.theme==='interior'||(paths[this.id]||[]).some(([a,b,w,h])=>x>=a&&x<a+w&&y>=b&&y<b+h)||(this.id==='village'&&Math.hypot(x-13,y-13)<3.6)}
 buildBase(){const m=this.map,w=(m.w+m.h)*32+64,h=(m.w+m.h)*16+64;this.outerTexture=texture(m.theme,false,0);this.baseOrigin={x:m.h*32+32,y:32};this.base=document.createElement('canvas');this.base.width=w*2;this.base.height=h*2;const c=this.base.getContext('2d'),ground=Array.from({length:5},(_,i)=>texture(m.theme,false,i)),stone=Array.from({length:5},(_,i)=>texture(m.theme,true,i));
  c.setTransform(2,1,-2,1,this.baseOrigin.x*2,this.baseOrigin.y*2);for(let y=0;y<m.h;y++)for(let x=0;x<m.w;x++){const path=this.onPath(x,y),variation=Math.floor(hash(x,y)*5);c.drawImage((path?stone:ground)[variation],(x-.5)*TILE,(y-.5)*TILE,TILE,TILE);if(path&&m.theme!=='interior'){for(const [dx,dy]of[[1,0],[-1,0],[0,1],[0,-1]])if(!this.onPath(x+dx,y+dy)){c.fillStyle='#a28a52';const xx=(x-.5)*TILE,yy=(y-.5)*TILE;c.fillRect(xx+(dx===1?29:0),yy+(dy===1?29:0),dx?3:32,dy?3:32);c.fillStyle='#ead49c';c.fillRect(xx+(dx===1?29:dx===-1?2:0),yy+(dy===1?29:dy===-1?2:0),dx?1:32,dy?1:32)}}}
  if(m.theme==='interior'){c.fillStyle='#66373b';c.fillRect(6*TILE,8*TILE,5*TILE,4*TILE);c.strokeStyle='#caa366';c.lineWidth=3;c.strokeRect(6*TILE+5,8*TILE+5,5*TILE-10,4*TILE-10);for(let i=0;i<6;i++){c.strokeStyle='#c49c6266';c.lineWidth=.8;c.strokeRect(6*TILE+10+i*3,8*TILE+10+i*3,5*TILE-20-i*6,4*TILE-20-i*6)}star(c,8.5*TILE,10*TILE,'#cfb77b',27);}
  if(this.id==='village'){const cx=13*TILE,cy=13*TILE;for(const [r,col,lw]of[[77,'#a99464',8],[72,'#e4d2a5',3],[64,'#aa915d',2],[41,'#aa915d',1]]){c.strokeStyle=col;c.lineWidth=lw;c.beginPath();c.arc(cx,cy,r,0,Math.PI*2);c.stroke()}for(let i=0;i<16;i++){const a=i*Math.PI/8;star(c,cx+Math.cos(a)*58,cy+Math.sin(a)*58,'#a28d5d',3)}star(c,cx,cy,'#b59451',34);star(c,cx,cy,'#ead49d',24);}
  if(m.theme==='beach'){c.fillStyle='#4a9ca3';c.fillRect(-16,(m.h-3)*TILE,m.w*TILE,3*TILE);c.fillStyle='#84bdb9';c.fillRect(-16,(m.h-3)*TILE,m.w*TILE,12);c.fillStyle='#e8dcb1';c.fillRect(-16,(m.h-3)*TILE-2,m.w*TILE,4);for(let i=0;i<100;i++){c.fillStyle='#d3e6d549';c.fillRect(hash(i,3)*m.w*TILE,(m.h-3)*TILE+12+hash(i,1)*70,8+hash(i,6)*20,1)}c.fillStyle='#7d5736';c.fillRect(1*TILE,11*TILE,2*TILE,6*TILE);for(let i=0;i<22;i++){c.fillStyle=i%2?'#b89b65':'#b08b54';c.fillRect(TILE+2,11*TILE+i*8,2*TILE-4,7)}}
  this.decor=[];if(m.theme!=='interior'&&m.theme!=='ruins'){for(let y=2;y<m.h-1;y+=2)for(let x=1;x<m.w-1;x+=2){if(x>2&&x<m.w-3&&y>3&&y<m.h-3)continue;if(m.theme==='beach'&&y>20)continue;const xx=x+(hash(x,y)-.5)*.45,yy=y+(hash(y,x)-.5)*.45;if(m.entities.some(e=>Math.hypot(xx-e.x,yy-e.y)<2.7))continue;this.decor.push({x:xx,y:yy,type:'tree'})}for(let i=0;i<110;i++){const x=1+hash(i,13)*(m.w-2),y=3+hash(i,74)*(m.h-5);if(blocked(m,x,y)||this.onPath(Math.round(x),Math.round(y))||(m.theme==='beach'&&y>21))continue;c.fillStyle='#344f2866';c.fillRect(x*TILE,y*TILE,2,5);if(i%3===0){c.fillStyle=['#e8c959','#d8c5ce','#dce2b0'][i%3];for(let k=0;k<4;k++)c.fillRect(x*TILE+Math.cos(k*1.57)*2,y*TILE+Math.sin(k*1.57)*2,2,2)}}}
  if(this.id==='village')for(const p of[[9.5,10],[16,10],[10,17],[17,16],[3,12],[22.7,12]])this.decor.push({x:p[0],y:p[1],type:'lantern'});
  if(this.id==='ruins')for(const p of[[7,5],[15,5],[7,13],[15,13]])this.decor.push({x:p[0],y:p[1],type:'lantern'});
 }
 drawBuilding(c,b){const front=toIso(b.x+b.w-.5,b.y+b.h-.5),width=(b.w+b.h)*TILE*1.04,kind=this.id==='village'?(b.name==='무기점'?'smith':b.name==='의상실'?'tailor':'home'):'inn';box(c,b.x-.5,b.y-.5,b.w,b.h,5,['#cbb88d','#9c8359','#786a4e']);const heroPoint=toIso(this.player.x,this.player.y),behind=this.player.x+this.player.y<b.x+b.w+b.y+b.h-1&&Math.abs(heroPoint.x-front.x)<width*.5&&heroPoint.y<front.y&&heroPoint.y>front.y-width*.97;
  c.save();if(behind)c.globalAlpha=.37;if(!sprite(c,'environment',kind,front.x,front.y-3,{width,flip:true})){box(c,b.x-.5,b.y-.5,b.w,b.h,80,['#647f72','#d5c098','#987b54'])}c.restore();}
 drawFurniture(c,f){const center=toIso(f.x+f.w/2-.5,f.y+f.h/2-.5),front=toIso(f.x+f.w-.5,f.y+f.h-.5);if(f.kind==='weapons'){box(c,f.x-.5,f.y-.5,f.w,f.h,39,['#aa8658','#876236','#684a29']);for(let i=0;i<3;i++){const p=toIso(f.x+i*.8,f.y+1.5);weaponIcon(c,p.x,p.y-37,D.items.find(item=>item.id===['iron','silver','starblade'][i]),1.15)}return}if(['bed','forge','clothes'].includes(f.kind)){sprite(c,'environment',f.kind,center.x,front.y,{width:(f.w+f.h)*TILE*.8,flip:true});return}if(f.kind==='counter'||f.kind==='table'){const b=box(c,f.x-.5,f.y-.5,f.w,f.h,29,['#bda072','#937041','#70502e']);c.strokeStyle='#dccc9e';c.lineWidth=1;for(let i=0;i<3;i++){const a=toIso(f.x,f.y+i*.25),d=toIso(f.x+f.w-1,f.y+i*.25);c.beginPath();c.moveTo(a.x,a.y-30);c.lineTo(d.x,d.y-30);c.stroke()}ellipse(c,'#ddc496',center.x,center.y-31,9,4);return}box(c,f.x-.5,f.y-.5,f.w,f.h,58,['#ad8655','#8c653a','#694a2b']);c.fillStyle='#f1cb6d';c.fillRect(front.x-22,front.y-33,3,4);c.fillRect(front.x-13,front.y-29,3,4);}
 drawEntity(c,e){const p=toIso(e.x,e.y);if(e.type==='npc'){const style={mia:'cape','smith-shop':'armor','tailor-shop':'mage',lucy:'tunic',amy:'ranger'}[e.id]||'tunic';hero(c,p.x,p.y,{outfit:{style},avatar:e.id==='smith-shop'?'jun':'mina',direction:'down',scale:1.15});}if(e.type==='monster')monster(c,p.x,p.y,e,this.time,1.15);if(e.type==='chest')chest(c,p.x,p.y,e.id==='key-chest'?this.state.key:this.state.choices?.['forest-chest']);if(e.type==='beacon'){c.save();c.filter=`saturate(${this.state.stars.length/3})`;sprite(c,'environment','beacon',p.x,p.y,{width:120});c.restore();for(let i=0;i<this.state.stars.length;i++){const x=p.x+(i-1)*31,y=p.y-66-(i===1?22:0);ellipse(c,'#ffe3a224',x,y,17,20);star(c,x,y+Math.sin(this.time*1.2+i)*2,'#ffe7ac',7)}}if(e.type==='door'){ellipse(c,'#fff0a01e',p.x,p.y,17,7);c.strokeStyle='#f0d49b80';c.lineWidth=1;c.beginPath();c.ellipse(p.x,p.y,13,6,0,0,Math.PI*2);c.stroke();if(e.id==='ruin-gate')sprite(c,'monster','portal',p.x,p.y,{height:105});}}
 drawWalls(c){const m=this.map;if(m.theme!=='interior')return;const xend=m.w-1.5,yend=m.h-1.5;box(c,.5,1.5,xend-.5,.4,64,['#c3a06d','#d3bd95','#816144']);box(c,.5,1.5,.4,yend-1.5,64,['#c3a06d','#b5a081','#715336']);for(let i=2;i<m.w-1;i+=3){const p=toIso(i,1.6);poly(c,[{x:p.x-14,y:p.y-57},{x:p.x+14,y:p.y-43},{x:p.x+14,y:p.y-20},{x:p.x-14,y:p.y-34}],'#79a7a4','#e3c892');c.strokeStyle='#bd9056';c.beginPath();c.moveTo(p.x,p.y-50);c.lineTo(p.x,p.y-27);c.stroke()}for(let i=2;i<m.h-1;i+=3){const p=toIso(.7,i);sprite(c,'environment','lantern',p.x,p.y-20,{height:36});}}
 frame(now){const dt=Math.min(.045,(now-this.last)/1000);this.last=now;this.time+=dt;const p=this.player;
  if(this.enabled){const sx=this.joy.x+(this.keys.has('d')||this.keys.has('arrowright')?1:0)-(this.keys.has('a')||this.keys.has('arrowleft')?1:0),sy=this.joy.y+(this.keys.has('s')||this.keys.has('arrowdown')?1:0)-(this.keys.has('w')||this.keys.has('arrowup')?1:0);let dx=0,dy=0;const manual=Math.hypot(sx,sy)>.12;
   if(manual){this.path=[];this.target=null;const v=screenMovement(sx,sy);dx=v.x;dy=v.y}else if(this.path.length){const n=this.path[0],d=Math.hypot(n.x-p.x,n.y-p.y);if(d<.08){p.x=n.x;p.y=n.y;this.path.shift();if(!this.path.length&&this.target){const target=this.target;this.target=null;this.cb.onInteract(target)}}else{dx=(n.x-p.x)/d;dy=(n.y-p.y)/d;}}
   this.moving=Math.hypot(dx,dy)>.1;if(this.moving&&this.enabled){const speed=(this.keys.has('shift')?5.6:4.1)*dt,nx=p.x+dx*speed,ny=p.y+dy*speed;const free=(x,y)=>!blocked(this.map,Math.round(x-.21),Math.round(y-.16))&&!blocked(this.map,Math.round(x+.21),Math.round(y+.16));if(free(nx,p.y))p.x=nx;if(free(p.x,ny))p.y=ny;this.direction=screenDirection(dx,dy);}
  }else this.moving=false;
  const near=this.map.entities.filter(e=>!this.defeated.has(e.id)&&this.distance(e)<1.8).sort((a,b)=>this.distance(a)-this.distance(b))[0]||null;if(near?.id!==this.near?.id){this.near=near;this.cb.onNear?.(near)}const target=toIso(p.x,p.y);this.camera.x+=(target.x-this.camera.x)*Math.min(1,dt*7);this.camera.y+=(target.y-this.camera.y)*Math.min(1,dt*7);this.draw();const points=this.map.entities.filter(e=>!this.defeated.has(e.id)).map(e=>{const pt=this.project(e.x,e.y);pt.y-=(e.type==='npc'?80:e.type==='monster'?(e.boss?108:64):e.type==='beacon'?104:40)*this.zoom;return{...pt,id:e.id,visible:pt.x>25&&pt.x<this.w-25&&pt.y>125&&pt.y<this.h-120}});this.cb.onMarkers?.(points);this.canvas.dataset.position=`${p.x.toFixed(1)},${p.y.toFixed(1)}`;this.canvas.dataset.map=this.id;this.canvas.dataset.projection='isometric';requestAnimationFrame(t=>this.frame(t));}
 draw(){const c=this.c,m=this.map;c.setTransform(this.dpr,0,0,this.dpr,0,0);c.imageSmoothingEnabled=true;rect(c,m.theme==='interior'?'#282619':m.theme==='ruins'?'#3c4845':'#526844',0,0,this.w,this.h);c.save();c.translate(this.w/2-this.camera.x*this.zoom,this.h*.54-this.camera.y*this.zoom);c.scale(this.zoom,this.zoom);if(m.theme!=='interior'){c.fillStyle=c.createPattern(this.outerTexture,'repeat');c.fillRect(this.camera.x-this.w/this.zoom,this.camera.y-this.h/this.zoom,this.w*2/this.zoom,this.h*2/this.zoom)}c.drawImage(this.base,-this.baseOrigin.x,-this.baseOrigin.y,this.base.width/2,this.base.height/2);this.drawWalls(c);
  const layers=[...this.decor.map(e=>({...e,depth:e.x+e.y})),...(m.buildings||[]).map(b=>({...b,type:'building',depth:b.x+b.w+b.y+b.h-1})),...(m.furniture||[]).map(b=>({...b,type:'furniture',depth:b.x+b.w+b.y+b.h-1})),...m.entities.filter(e=>!this.defeated.has(e.id)).map(e=>({...e,depth:e.x+e.y})),{type:'player',depth:this.player.x+this.player.y}].sort((a,b)=>a.depth-b.depth);
  for(const e of layers){const p=toIso(e.x||0,e.y||0);if(e.type==='tree'){const player=toIso(this.player.x,this.player.y),fade=e.depth>this.player.x+this.player.y&&Math.abs(p.x-player.x)<65&&p.y-player.y>0&&p.y-player.y<145;c.save();if(fade)c.globalAlpha=.35;tree(c,p.x,p.y,m.theme==='mountain'?2:m.theme==='forest'?1:0);c.restore()}else if(e.type==='lantern'){ellipse(c,'#2d301b28',p.x+6,p.y,18,7);sprite(c,'environment','lantern',p.x,p.y,{height:78});}else if(e.type==='building')this.drawBuilding(c,e);else if(e.type==='furniture')this.drawFurniture(c,e);else if(e.type==='player'){const p=toIso(this.player.x,this.player.y);c.strokeStyle='#fee4a275';c.lineWidth=1;c.beginPath();c.ellipse(p.x,p.y,19,8,0,0,Math.PI*2);c.stroke();hero(c,p.x,p.y,{outfit:D.items.find(i=>i.id===this.state.outfit),weapon:D.items.find(i=>i.id===this.state.weapon),avatar:this.state.avatar,direction:this.direction,walk:this.moving?this.time*13:0,scale:1.32})}else this.drawEntity(c,e)}
  if(this.state.festival&&this.id==='village'){for(let row=0;row<3;row++){const a=toIso(4,8+row*5),b=toIso(24,8+row*5);c.strokeStyle='#6c583f';c.lineWidth=.8;c.beginPath();for(let i=0;i<=20;i++){const t=i/20;c.lineTo(a.x+(b.x-a.x)*t,a.y+(b.y-a.y)*t-50+Math.sin(t*Math.PI)*18)}c.stroke();for(let i=0;i<20;i++){const t=i/20,x=a.x+(b.x-a.x)*t,y=a.y+(b.y-a.y)*t-50+Math.sin(t*Math.PI)*18;star(c,x,y,['#ffe29f','#d89ca9','#98beb0'][i%3],4)}}for(let i=0;i<30;i++){const p=toIso(4+hash(i,4)*19,7+hash(i,5)*15);star(c,p.x,p.y-22+Math.sin(this.time+i)*6,'#ffe3a080',2)}}c.restore();
  const vignette=c.createRadialGradient(this.w/2,this.h*.45,this.w*.25,this.w/2,this.h*.5,Math.max(this.w,this.h)*.75);vignette.addColorStop(0,'#322c1700');vignette.addColorStop(1,'#2d311722');c.fillStyle=vignette;c.fillRect(0,0,this.w,this.h);}
}
