(()=>{'use strict';
const D=window.KittyData,C=window.KittyCore,S=window.KittySpeech,$=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const KEY='little-lives-v3',ART='assets/animal-town/life/';
const esc=t=>String(t??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state=C.init();try{const raw=localStorage.getItem(KEY);if(raw)state=C.normalize(JSON.parse(raw));else {const old=JSON.parse(localStorage.getItem('tori-care-v1')||'null');if(old){state.gold=Math.max(45,Number(old.gold)||0);state.xp=Math.max(0,Number(old.xp)||0);state.owned=Array.from(new Set([...state.owned,...(old.owned||[]).map(i=>['mint','rain','princess'][i]).filter(Boolean)]));state.name='Tori';state.sound=old.sound!==false;}state.legacyMovies=['home','kindergarten','restaurant','airport','hotel'];}}catch{}
let busy=false,playToy='ribbon',hits=0,toastTimer,shopTab='food',starter={breed:'corgi',species:'cat',name:state.name||'Tori',outfit:'mint'},adoptionStep=0;
const icons={
 trophy:'M7 3h10v6a5 5 0 01-10 0ZM7 5H3v3a4 4 0 004 4M17 5h4v3a4 4 0 01-4 4M12 14v5M7 21h10',
 chair:'M6 12V6a3 3 0 013-3h6a3 3 0 013 3v6M3 11h4v6h10v-6h4v9H3ZM6 20v2M18 20v2',
 heart:'M12 20s-8-5-8-11a4 4 0 018-1 4 4 0 018 1c0 6-8 11-8 11Z',
 shop:'M4 9h16v11H4ZM3 9l2-6h14l2 6M9 20v-7h6v7',
 map:'M3 5l6-2 6 2 6-2v16l-6 2-6-2-6 2ZM9 3v16M15 5v16',
 shirt:'M8 3l4 3 4-3 6 4-3 5-3-2v11H8V10l-3 2-3-5Z',
 book:'M12 5c-3-3-7-2-10-1v15c4-2 7-2 10 1 3-3 6-3 10-1V4c-3-1-7-2-10 1ZM12 5v15',
 moon:'M20 14A9 9 0 0110 3a9 9 0 1010 11Z',
 volume:'M3 9h4l5-5v16l-5-5H3ZM16 8q4 4 0 8M19 5q7 7 0 14',
 gear:'M9 3h6l1 4 4 2v6l-4 2-1 4H9l-1-4-4-2V9l4-2ZM12 9a3 3 0 100 6 3 3 0 000-6'
};
const icon=id=>'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="'+(icons[id]||icons.heart)+'"/></svg>';
const btn=(text,cmd,arg='',cls='primary')=>'<button class="'+cls+'" data-cmd="'+cmd+'" data-arg="'+esc(arg)+'">'+esc(text)+'</button>';
const item=(cell,extra='')=>'<span class="item-art '+extra+'" style="background-position:'+(cell%3)*50+'% '+Math.floor(cell/3)*50+'%"></span>';
const outfitIndex=id=>D.goods.find(g=>g.id===id)?.outfit||0;
const petArt=(species=state.species,age=C.ageStage(state),outfit=outfitIndex(state.outfit),cls='')=>'<div class="pet-atlas '+cls+'" data-species="'+species+'" data-age="'+age+'" data-outfit="'+outfit+'"></div>';
function persist(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('Saving is unavailable in this browser. Keep this tab open.');}}
function speak(text){return S.speak(text,{enabled:state.sound,voice:state.voice})}
function toast(text){$('#toast').textContent=text;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,2800)}
function bubble(text,read=false){$('#bubble').textContent=text;if(read)speak(text)}
function spark(){for(let i=0;i<7;i++){const p=document.createElement('span');p.className='spark';p.textContent='✦';p.style.left=30+Math.random()*40+'%';p.style.top=45+Math.random()*22+'%';p.style.animationDelay=i*.06+'s';$('#particles').append(p);setTimeout(()=>p.remove(),2200)}}
function paint(){requestAnimationFrame(()=>{$$('.pet-atlas').forEach(el=>{if(el.id==='world'&&$('#game').classList.contains('outing'))return;const sp=el.dataset.species||state.species,row=Number(el.dataset.age??C.ageStage(state)),col=Number(el.dataset.outfit??outfitIndex(state.outfit));const r=el.getBoundingClientRect();if(!r.width||!r.height)return;if(el.classList.contains('pet-thumb')&&sp==='dog'){el.style.backgroundImage='url("assets/animal-town/models/previews/profile-'+(state.breed||'corgi')+'.png")';el.style.backgroundSize='240%';el.style.backgroundPosition='50% 42%';return;}if(sp==='cat'){el.style.backgroundImage='url("'+ART+'cat-hd-'+row+'-'+col+'.png")';el.style.backgroundSize='cover';el.style.backgroundPosition='center';el.style.backgroundRepeat='no-repeat';return;}const rects=[{y:3,h:436},{y:452,h:475},{y:938,h:593}],rect=rects[row]||rects[0],x=[3,346,691][col]||3,cw=329,ch=rect.h,z=Math.max(r.width/cw,r.height/ch)*1.02;el.style.backgroundImage='url("'+ART+sp+'-growth.png")';el.style.backgroundSize=(1024*z)+'px '+(1536*z)+'px';el.style.backgroundPosition=((r.width-cw*z)/2-x*z)+'px '+((r.height-ch*z)/2-rect.y*z)+'px';el.style.backgroundRepeat='no-repeat';});});}
window.addEventListener('resize',paint);
function render(){const lv=C.level(state);$('#hudXp').style.width=(state.xp%80/80*100)+'%';$('#hudXpText').textContent='경험치 '+state.xp%80+' / 80';$('#dailyCount').textContent=[state.fedToday>0,state.playedToday>0,state.pettedToday,state.actions>0].filter(Boolean).length+' / 4';$('#growthCount').textContent=state.score+'점';$('#memoryCount').textContent=state.memories.length*3+'장';$('#petName').textContent=state.name;$('#ageText').textContent='Lv. '+lv+' · '+C.age(state)+' months';$('#gold').textContent=state.gold;$('#level').textContent='Lv. '+lv;$('#xp').style.width=(state.xp%80)/80*100+'%';$('#xpText').textContent=state.xp%80+' / 80 XP';$('#score').textContent=state.score;$('#day').textContent='DAY '+state.day;$('#slots').textContent=Math.max(0,3-state.actions)+' outings left';
 $('#needs').innerHTML=[['Food',state.food,'pantry','Feed'],['Energy',state.energy,'rest','Sleep'],['Calm',100-state.stress,'toys','Play'],['Health',state.health,'clinic','Vet']].map(([name,value,cmd,action])=>'<button data-cmd="'+cmd+'" class="'+(value<40?'low':'')+'" aria-label="'+name+' '+value+' percent. '+action+'"><span>'+name+' <strong>'+value+'</strong></span><i><b style="width:'+value+'%"></b></i><small>'+action+' →</small></button>').join('');
 const goal=D.goods.find(x=>x.id===state.goal)||D.goods.find(x=>x.id==='bed');$('#goal').innerHTML=item(goal.cell??6)+'<span><small>MY NEXT WISH</small><b>'+esc(goal.name)+'</b><em>'+Math.min(state.gold,C.price(state,goal))+' / '+C.price(state,goal)+' G</em></span>';
 let prompt='A little care before a big adventure.';if(state.active)prompt='Your story is waiting. Continue where you left off.';else if(state.actions>=3)prompt='A lovely full day. Time to sleep.';else if(state.food<35)prompt='A hungry little tummy. Let’s have a meal.';else if(state.stress>55)prompt='A little stressed. Let’s play gently.';else if(state.energy<25)prompt='Those eyes look sleepy. Time to rest.';else if(C.illness(state).feverStatus==='a mild fever')prompt='A little cough today. Dr. Pip can help.';
 $('#homePrompt').innerHTML='<div class="home-tools">'+btn('My 3D Room','room','','secondary')+btn('Save / Load','saves','','secondary')+'</div><small>'+ (state.active?'YOUR STORY':'TODAY WITH '+esc(state.name.toUpperCase()))+'</small>'+esc(prompt)+(state.active?btn('Resume','resume','','resume-link'):'');
 $('#furnishings').innerHTML=Object.entries(state.decor).filter(([slot])=>slot!=='room').map(([slot,id])=>{const g=D.goods.find(x=>x.id===id);return '<div class="furnishing '+slot+'">'+item(g.cell)+'<small>'+esc(g.name)+'</small></div>'}).join('');
 $('#game').classList.toggle('room-upgraded',!!state.decor.room);persist();paint();
}
function home(){window.KittyPreview?.close();window.KittyTown?.close();$('#game').classList.remove('town-mode');readId++;S.stop();answerControls(false);$('#episode').hidden=true;$('#game').classList.remove('outing');$('#world').classList.add('pet-atlas');render();room();}
function close(){window.KittyPreview?.close();window.KittyArcade?.stop();S.stop();const video=$('#sheetContent video');if(video)video.pause();$('#sheetLayer').hidden=true;if($('#episode').hidden)home();}
function sheet(title,tag,html){window.KittyPreview?.close();window.KittyArcade?.stop();S.stop();$('#sheetTitle').textContent=title;$('#sheetTag').textContent=tag;$('#sheetContent').innerHTML=html;$('#sheetLayer').hidden=false;$('#sheetLayer .sheet').scrollTop=0;paint();}
function adoption(){const sp=starter.species;$('#adoption').hidden=false;$('#adoption').innerHTML='<small>LITTLE LIVES · GROW TOGETHER</small><h1>어떤 친구와<br>함께할까요?</h1><p>A first hello. A whole life together.</p><div class="species-row">'+['cat','dog'].map(type=>'<button class="species-card '+(sp===type?'selected':'')+'" data-cmd="species" data-arg="'+type+'" aria-pressed="'+(sp===type)+'">'+petArt(type,0,outfitIndex(starter.outfit))+'<b>'+(type==='cat'?'A kitten':'A puppy')+'</b></button>').join('')+'</div>'+ (sp==='dog'?'<div class="breed-row">'+['corgi','pug','shepherd','shiba'].map(id=>'<button class="'+(starter.breed===id?'selected':'')+'" data-cmd="starterBreed" data-arg="'+id+'">'+id+'</button>').join('')+'</div>':'')+'<label class="name-label" for="adoptName">What is your friend’s name?</label><input id="adoptName" maxlength="18" value="'+esc(starter.name)+'" autocomplete="off"><label class="name-label">Choose a first outfit · both are yours</label><div class="starter-row">'+[['mint','Mint Overalls'],['rain','Sunny Raincoat']].map(([id,label])=>'<button class="'+(starter.outfit===id?'selected':'')+'" data-cmd="starter" data-arg="'+id+'">'+label+'</button>').join('')+'</div>'+btn('Bring my friend home','adopt');paint();}
function updateStarter(){starter.name=$('#adoptName')?.value||starter.name;}
function adopt(){updateStarter();const r=C.adopt(state,starter.species,starter.name,starter.outfit);if(!r.ok){toast(r.message);return}state.breed=starter.breed;$('#adoption').hidden=true;home();bubble('Hi! I am '+state.name+'. Let’s be friends!',true);spark();}
function dailyTasks(){const tasks=[['밥 주기',state.fedToday>0,'pantry'],['함께 놀기',state.playedToday>0,'toys'],['쓰다듬기',state.pettedToday,'pet'],['영어 이야기 마치기',state.actions>0,'goOut']];sheet('오늘 할 일','매일 함께하는 작은 습관','<div class="daily-list">'+tasks.map(([name,done,cmd])=>btn((done?'완료 · ':'도전 · ')+name,cmd,'',done?'secondary':'primary')).join('')+'</div><p>밥 주기·놀아주기·쓰다듬기를 모두 하면 성장 점수 10점을 받아요. 영어 이야기를 마치면 경험치와 골드도 얻어요.</p>');}
function care(){if(busy)return;sheet('A little love','CARE FOR '+state.name.toUpperCase(),'<p>Food, play, and a good sleep make a happy little friend.</p><div class="care-grid"><button data-cmd="pantry">'+item(0)+'<b>Feed</b><small>Choose a tasty meal</small></button><button data-cmd="toys">'+item(4)+'<b>Play</b><small>Help your friend relax</small></button><button data-cmd="pet">'+icon('heart')+'<b>Cuddle</b><small>A gentle little moment</small></button><button data-cmd="sleep">'+icon('moon')+'<b>Sleep</b><small>Restore energy · next day</small></button></div><p class="fine">Fresh basic food arrives each morning. Your friend does not get sick while the game is closed.</p>');}
function pantry(){sheet('What would you like?','TIME TO EAT','<div class="product-grid">'+D.goods.filter(g=>g.type==='food').map(g=>'<article class="product">'+item(g.cell)+'<h3>'+g.name+'</h3><p>Food +'+g.food+' · Calm +'+(-g.stress)+'<br>In your pantry: '+(state.pantry[g.id]||0)+'</p><button data-cmd="feed" data-arg="'+g.id+'" '+(!state.pantry[g.id]?'disabled':'')+'>Feed '+esc(state.name)+'</button></article>').join('')+'</div>'+btn('Buy more food','shop','food','secondary'));}
function feed(id){if(busy)return;const r=C.feed(state,id);if(!r.ok){toast(r.message);return}close();busy=true;const g=D.goods.find(x=>x.id===id);$('#prop').innerHTML=item(g.cell);$('#prop').hidden=false;bubble('Yum! Thank you for my food.',true);spark();render();setTimeout(()=>{busy=false;$('#prop').hidden=true;bubble(r.message);if(C.careBonus(state))toast('Lovely care! +10 growth points');render();},1600)}
function pet(){if(busy||!state.adopted)return;C.pet(state);C.careBonus(state);if(!$('#sheetLayer').hidden)close();bubble('That feels nice. I love you!',true);spark();render();}
function toys(){sheet('Let’s play together','LESS STRESS, MORE SMILES',btn('Play fetch · free ball','play','ribbon')+'<div class="product-grid">'+D.goods.filter(g=>g.type==='toy'&&state.owned.includes(g.id)).map(g=>'<article class="product">'+item(g.cell)+'<h3>'+g.name+'</h3><p>'+g.description+'</p>'+btn('Play','play',g.id,'secondary')+'</article>').join('')+'</div>'+btn('Find a new toy','shop','toy','secondary'));}
function play(id){if(state.energy<10){toast('Let’s sleep first.');return}if(id!=='ribbon'&&!state.owned.includes(id)){toast('Buy this toy first.');return}playToy=id;close();room();window.KittyRoom.fetchBall();}
function moveToy(){$('#toyTarget').style.left=(9+Math.random()*62)+'%';$('#toyTarget').style.top=(43+Math.random()*26)+'%';}
function catchToy(){hits++;$('#playCount').textContent=hits+' / 5';spark();if(hits>=5){$('#playLayer').hidden=true;const r=C.play(state,playToy);C.careBonus(state);bubble(r.message,true);render();}else moveToy();}
function sleep(){if(busy)return;const r=C.sleep(state);if(!r.ok){toast(r.message);return}close();busy=true;$('#game').classList.add('sleeping');bubble('Good night. Sweet dreams!',true);render();setTimeout(()=>{busy=false;$('#game').classList.remove('sleeping');bubble('Good morning! I am '+C.age(state)+' months old.');render();if(r.grew){spark();growth('Look how I have grown!')}},2400);}
function shop(type='food'){if(type==='furniture'){furnitureShop();return;}shopTab=type;const list=D.goods.filter(g=>g.type===type);sheet('A little something lovely','YOUR GOLD · '+state.gold+' G',(C.redCount(state)>=2?'<p class="penalty">Prices ×2 · Two or more needs are red. Care first to restore normal prices.</p>'+btn('Care now','care','','secondary'):'')+'<div class="tabs">'+[['food','Food'],['toy','Toys'],['outfit','Outfits'],['furniture','My Room']].map(([id,n])=>'<button class="'+(type===id?'active':'')+'" data-cmd="shop" data-arg="'+id+'">'+n+'</button>').join('')+'</div><div class="product-grid">'+list.map(g=>{const owned=state.owned.includes(g.id),wear=state.outfit===g.id||Object.values(state.decor).includes(g.id);return '<article class="product">'+(g.type==='outfit'?petArt(state.species,C.ageStage(state),g.outfit):item(g.cell))+'<h3>'+g.name+'</h3><p>'+g.description+'</p><button data-cmd="'+(owned&&g.type!=='toy'?'equip':'buy')+'" data-arg="'+g.id+'" class="'+(wear?'wearing':'')+'" '+(owned&&g.type==='toy'?'disabled':'')+'>'+(wear?'In use':owned?(g.type==='outfit'?'Wear':g.type==='furniture'?'Place in room':'Owned'):C.price(state,g)+' G · Buy')+'</button>'+(!owned&&g.type!=='food'?'<button data-cmd="wish" data-arg="'+g.id+'">Save as my wish</button>':'')+'</article>'}).join('')+'</div>');}
function buy(id){const r=C.buy(state,id);toast(r.message);if(r.ok){spark();render();shop(shopTab)}}
function equip(id){const r=C.equip(state,id);if(r.ok){close();bubble('Do you like my '+D.goods.find(g=>g.id===id).name+'?',true);spark();render();if(D.goods.find(g=>g.id===id).type==='furniture')room()}else toast(r.message)}
function closet(){shop('outfit')}
function growth(title='Growing together'){sheet(title,'DAY '+state.day+' · '+state.name.toUpperCase(),'<div class="stats-grid">'+[['Level',C.level(state)],['Growth',state.score],['Bond',state.bond],['Kindness',state.skills.kindness],['Courage',state.skills.confidence],['English',Object.keys(state.mastery).length]].map(([k,v])=>'<div><b>'+v+'</b><small>'+k+'</small></div>').join('')+'</div><div class="timeline">'+[0,1,2].map((a)=>'<div>'+petArt(state.species,a,outfitIndex(state.outfit))+'<b>'+['Little one','Growing up','Young adult'][a]+'</b><small>'+['3–5 months','6–11 months','12+ months'][a]+'</small></div>').join('')+'</div><p>English stories earn XP, growth points, and gold. Care builds your bond. Every 80 XP brings a new level.</p><p>Growth gifts: 100 points → 20 G · 250 points → 40 G · 500 points → 60 G. Each gift is earned once.</p><p class="fine">Story time: three days are one month of growing up. Appearance changes at six and twelve months.</p>'+btn('Open my English notebook','notebook','','secondary'));}
function notebook(){const entries=Object.entries(state.review);sheet('Words for another day','MY ENGLISH NOTEBOOK','<p>'+Object.keys(state.mastery).length+' expressions practiced. Mistakes are a chance to learn.</p>'+(entries.length?entries.map(([id,r])=>'<button class="secondary" data-cmd="read" data-arg="'+esc(r.text)+'">'+esc(r.text)+'</button>').join(''):'<p>No words waiting for practice. Lovely work!</p>'));}
function outing(){if(busy)return;const html=btn('Walk around town','walk')+btn('Play at the Arcade','arcade')+(state.active?btn('Continue my story','resume'):'')+'<p>'+Math.max(0,3-state.actions)+' outings left today. Choose a place to make a memory.</p>'+D.locations.map(l=>'<button class="place-card" data-cmd="place" data-arg="'+l.id+'" '+(C.level(state)<l.level?'disabled':'')+'><span class="place-thumb" style="background-image:url(&quot;'+(l.id==='clinic'||l.id==='forest'?ART+'places.png':l.photo)+'&quot;);'+(l.id==='clinic'||l.id==='forest'?'background-size:200% 100%;background-position:'+(l.id==='clinic'?'left':'right')+' center;':'')+'"></span><b>'+l.name+'</b><small>'+l.subtitle+'</small><em>'+(C.level(state)<l.level?'Level '+l.level+' to unlock':D.episodes.filter(e=>e.location===l.id).length+' stories')+'</em></button>').join('');sheet('Where shall we go?','A DAY WITH '+state.name.toUpperCase(),html);}
function place(id){const l=D.locations.find(x=>x.id===id);sheet(l.name,'CHOOSE AN EPISODE',D.episodes.filter(e=>e.location===id).map(e=>'<button class="place-card" data-cmd="begin" data-arg="'+e.id+'" '+(C.level(state)<e.level?'disabled':'')+' style="padding-left:16px"><b>'+e.title+'</b><small>'+esc(C.expand(state,e.story))+'</small><em>'+e.nodes.length+' conversations · '+e.reward+' G · Lv.'+e.level+'</em></button>').join(''));}
function begin(id){const r=C.begin(state,id);if(!r.ok){toast(r.message);return}persist();$('#sheetLayer').hidden=true;story();}
function scene(location){$('#game').classList.remove('room-main');$('#roomLayer').hidden=true;const l=D.locations.find(x=>x.id===location);$('#game').classList.add('outing');const w=$('#world');w.classList.remove('pet-atlas');if(townBackdrop[location]){w.style.backgroundImage='url("'+townBackdrop[location]+'")';w.style.backgroundSize='cover';w.style.backgroundPosition='center';return;}w.style.backgroundImage='url("'+(location==='clinic'||location==='forest'?ART+'places.png':l.photo)+'")';if(location==='clinic'||location==='forest'){w.style.backgroundSize='auto 100%';w.style.backgroundPosition=location==='clinic'?'left center':'right center';}else{w.style.backgroundSize='cover';w.style.backgroundPosition='center';}}
function story(){$('#translation')?.remove();$('#translateButton')?.remove();$('#feedback').classList.remove('wrong-feedback');const c=C.current(state);if(!c){home();return}$('#sheetLayer').hidden=true;$('#episode').hidden=false;scene(c.episode.location);$('#episodePlace').textContent=D.locations.find(l=>l.id===c.episode.location).name.toUpperCase();$('#episodeTitle').textContent=c.episode.title;$('#episodeCount').textContent=(state.active.index+1)+' / '+c.episode.nodes.length;$('#speaker').textContent=D.locations.find(l=>l.id===c.episode.location).npc;$('#context').textContent=C.expand(state,c.node.context);$('#line').textContent=C.expand(state,c.node.line);$('#line').insertAdjacentHTML('afterend','<button id="translateButton" aria-expanded="false" class="translate-button">해석 보기</button><p id="translation" class="translation" hidden></p>');$('#translation').textContent=D.translations[c.node.id];$('#translateButton').onclick=()=>{const el=$('#translation');el.hidden=!el.hidden;$('#translateButton').textContent=el.hidden?'해석 보기':'해석 숨기기';$('#translateButton').setAttribute('aria-expanded',String(!el.hidden));};$('#preferenceNote').textContent=c.node.preference?'Your choice changes the story':'';$('#hintButton').hidden=c.node.preference;$('#hint').hidden=!state.hints&&!state.active.needsRetry||!!c.node.preference;$('#hint').textContent='Say: '+C.expand(state,c.node.choices.find(x=>x.ok).text);$('#feedback').textContent=state.active.accepted?'Lovely! Your story continues.':state.active.needsRetry?'Listen, then try again.':'';$('#nextLine').hidden=!state.active.accepted;$('#nextLine').textContent=state.active.index===c.episode.nodes.length-1?'Finish our story':'Continue';
 const order=c.node.choices.map((x,i)=>i);const offset=state.active.index%order.length;order.push(...order.splice(0,offset));$('#choices').innerHTML=order.map(i=>'<button data-cmd="answer" data-arg="'+i+'" '+(state.active.accepted?'disabled':'')+'>'+esc(C.expand(state,c.node.choices[i].text))+'</button>').join('');
 $('#battleHud').hidden=!c.episode.battle;if(c.episode.battle){$('#battleHud').innerHTML='<div>Jelly Slime · '+(100-state.active.correct.length*20)+' HP<i><b style="width:'+(100-state.active.correct.length*20)+'%"></b></i></div><div>'+esc(state.name)+' · '+Math.max(0,90-state.active.mistakes*15)+' HP<i><b style="width:'+(100-state.active.mistakes/6*100)+'%"></b></i></div>';}
 $('#episode .dialogue').scrollTop=0;if(!state.active.accepted)speak(C.expand(state,c.node.line));persist();}
let readingAnswer=false,readId=0;
function answerControls(locked){readingAnswer=locked;$('#nextLine').disabled=locked;$('#listen').disabled=locked;$('#hintButton').disabled=locked;$$('#choices button').forEach(b=>b.disabled=locked||!!state.active?.accepted);}
async function readAnswer(text){const id=++readId;answerControls(true);const result=await speak(text);if(id!==readId)return;answerControls(false);if(result==='error'||result==='unavailable')$('#feedback').textContent='Audio unavailable. Read the sentence, then continue.';}
function answer(index){if(readingAnswer)return;const c=C.current(state);if(!c||state.active.accepted)return;const text=C.expand(state,c.node.choices[index]?.text||'');const r=C.answer(state,index);persist();if(r.retreat){S.wrong(state.sound);home();toast(r.message);return}story();const button=$('#choices [data-arg="'+index+'"]');if(!r.ok){button?.classList.add('wrong');$('#feedback').textContent=r.message;$('#feedback').classList.add('wrong-feedback');$('#hint').hidden=false;S.wrong(state.sound);readAnswer(C.expand(state,c.node.choices.find(x=>x.ok).text));return}$('#feedback').classList.remove('wrong-feedback');button?.classList.add('correct');readAnswer(text);spark();}
function next(){if(readingAnswer)return;const r=C.next(state);persist();if(!r.ok)return;if(r.finished){home();result(r)}else story();}
function pause(){S.stop();$('#episode').hidden=true;home();sheet('Your story is saved','TAKE A LITTLE BREAK',btn('Continue the story','resume')+btn('Leave this outing','leave','','secondary')+'<p class="fine">Leaving keeps your saved growth. This unfinished outing gives no reward.</p>');}
function result(r){const e=D.episodes.find(x=>x.id===r.episode);sheet(r.levelUp?'A new level!':'A little life, a big moment',e.title.toUpperCase(),'<div class="center-copy"><h3>'+esc(e.ending)+'</h3></div><div class="reward-row"><span>+'+r.xp+'<small>XP</small></span><span>+'+r.score+'<small>GROWTH</small></span><span>+'+r.gold+'<small>GOLD</small></span></div>'+(r.replay?'<p>You already earned this story’s reward today. Try a new story for more gold.</p>':'<p>Three little photographs have been added to your memory book.</p>'+(r.bonus?'<p>Growth milestone gift: +'+r.bonus+' G included!</p>':''))+btn('Open our three photos','memory',r.memory?.id||state.memories.find(m=>m.episode===e.id)?.id||'')+btn('Go home','home','','secondary'));spark();}
function memory(id){const m=state.memories.find(x=>x.id===id);if(!m){album();return}const e=D.episodes.find(x=>x.id===m.episode);const captions=['A little beginning','We did it together','A day to remember'];sheet(m.title,'DAY '+m.day+' · '+m.name.toUpperCase(),'<div class="memory-grid">'+m.photos.map((p,i)=>'<article class="memory-card">'+(['clinic','forest'].includes(m.location)?'<div class="memory-atlas" style="background-image:url('+ART+'memories.png);background-size:300% 200%;background-position:'+i*50+'% '+(m.location==='clinic'?0:100)+'%"></div>':'<img src="assets/animal-town/rewards/'+p+'.png" alt="'+esc(captions[i])+'">')+'<b>'+captions[i]+'</b><small>'+esc(i===0?m.name+' · '+m.age+' months old':i===1?'서로 도우며 용기를 냈어요.':'함께 만든 소중한 추억이에요.')+'</small></article>').join('')+'</div>'+btn('Back to our room','home'));}
function album(){sheet('Our memory book','LITTLE MOMENTS, FOREVER',(state.memories.length?state.memories.slice().reverse().map(m=>'<button class="place-card" style="padding-left:15px" data-cmd="memory" data-arg="'+m.id+'"><b>'+esc(m.title)+'</b><small>Day '+m.day+' · '+esc(m.name)+' · '+m.age+' months</small><em>3 photographs</em></button>').join(''):'<p class="empty">Your first photograph is waiting.<br>Choose an outing and make a memory.</p>')+btn('Earlier story movies','legacy','','secondary'));}
function legacy(){sheet('Earlier story movies','YOUR ORIGINAL COLLECTION','<p>New adventures make photo memories. Your earlier movies are still here.</p>'+['home','kindergarten','restaurant','airport','hotel'].map(id=>btn(id.charAt(0).toUpperCase()+id.slice(1),'movie',id,'secondary')).join(''));}
function movie(id){if(!['home','kindergarten','restaurant','airport','hotel'].includes(id))return;sheet('A familiar little story','EARLIER MOVIE','<video class="movie" controls playsinline src="assets/animal-town/videos/'+id+'/reward-30s.mp4"></video>');$('#sheetContent video').muted=!state.sound;}
function settings(){const voices=S.voices(),selected=S.preferred(state.voice);sheet('A comfortable little game','SETTINGS','<div class="settings-row"><span>English voice</span><select id="voiceSelect" aria-label="English voice">'+(voices.length?voices.map((v,i)=>'<option value="'+esc(v.voiceURI)+'" '+(v.voiceURI===selected?.voiceURI?'selected':'')+'>'+'목소리 '+(i+1)+' · '+(v.lang==='en-US'?'미국 영어':v.lang==='en-GB'?'영국 영어':'영어')+'</option>').join(''):'<option value="">System English</option>')+'</select></div>'+btn('목소리 미리 듣기','read','Hello, my little friend.','secondary')+'<div class="settings-row"><span>Sound</span>'+btn(state.sound?'On':'Off','sound','','toggle')+'</div><div class="settings-row"><span>Show easy reply help</span>'+btn(state.hints?'On':'Off','hints','','toggle')+'</div><p class="fine">An available English voice is selected explicitly, with normal speed and pitch. Voice quality depends on the voices installed on your device.</p>');}
document.addEventListener('change',e=>{if(e.target.id==='voiceSelect'){state.voice=e.target.value;persist();speak('Hello, my little friend.')}});
function arcade(){sheet('Little Arcade','PLAY & GROW', '<p>Play a round. Earn a little treat.</p>'+[['plane','Sky Pilot','Fly, dodge storms, and collect the word you hear.'],['bricks','Word Breaker','Bounce the ball. Break every word brick.'],['pairs','Word Pairs','Match English words with their Korean meanings.']].map(([id,title,description])=>'<button class="place-card" style="padding-left:16px" data-cmd="minigame" data-arg="'+id+'"><b>'+title+'</b><small>'+description+'</small><em>Win: +15 G · +20 XP · once per day</em></button>').join(''));}
function minigame(id){sheet('Ready, little player?','LITTLE ARCADE','<div id="arcadeMount"></div>');window.KittyArcade.start(id,$('#arcadeMount'),{speak,wrong:()=>S.wrong(state.sound),finish:won=>{const key='arcade:'+state.day+':'+id;let reward=false;C.careTick(state);if(won&&!state.claimed.includes(key)){state.claimed.push(key);state.gold+=15;state.xp+=20;state.score+=10;state.stress=Math.max(0,state.stress-8);reward=true;render();}render();return reward;}});}
let roomKey='',roomUnavailable=false,townBackdrop={};
function room(){if(!state.adopted||roomUnavailable)return;const key=JSON.stringify([state.species,state.breed,state.house,state.storedItems,state.outfit,C.ageStage(state),state.owned,state.homeLevel,state.roomLayout]);const host=$('#roomLayer');if(roomKey!==key||!host.querySelector('canvas')){const ok=window.KittyRoom.open(host,{state,save:persist,main:true,speak,onChange:()=>{roomKey='';room();window.KittyRoom.decorate();render()},onShop:()=>shop('furniture'),onUse:id=>{if(['bed','single','quilt'].includes(id)){sheet('Rest together','A COZY HOME',btn('Sleep & next day','sleep'));}else if(['fridge','stove','sink','counter'].includes(id))pantry();else if(['desk','shelf'].includes(id))place('library');else if(['ball','wand'].includes(id))play(id);else {pet();}},onPlay:()=>{const r=C.play(state,playToy);C.careBonus(state);render();toast(r.message)},onClose:()=>{$('#game').classList.remove('room-main');roomUnavailable=true;}});if(ok===false){roomUnavailable=true;return}roomKey=JSON.stringify([state.species,state.breed,state.house,state.storedItems,state.outfit,C.ageStage(state),state.owned,state.homeLevel,state.roomLayout]);}host.hidden=false;$('#game').classList.add('room-main');}
const modelThumb=model=>'<img class="model-thumb" src="assets/animal-town/models/previews/'+model+'.png" alt="" loading="lazy">';
let furnitureCategory='All',previewBreed='corgi';
function furnitureShop(category='All'){furnitureCategory=category;shopTab='furniture';const list=D.goods.filter(g=>g.type==='furniture'&&(category==='All'||g.category===category||(!g.model&&category==='Bedroom')));sheet('Furniture','YOUR GOLD · '+state.gold+' G','<div class="shop-tabs">'+['All','Living','Bedroom','Kitchen','Decor','Garden'].map(c=>btn(c,'furnitureShop',c,c===category?'primary':'secondary')).join('')+'</div><div class="product-grid">'+list.map(g=>'<article class="product">'+(g.model?modelThumb(g.model):item(g.cell))+'<h3>'+g.name+'</h3><p>'+(g.category||'Bedroom')+'</p>'+btn(state.owned.includes(g.id)?(state.storedItems.includes(g.id)?'Place in room':'In your room'):C.price(state,g)+' G · Buy','furnitureBuy',g.id)+'</article>').join('')+'</div>'+btn('Arrange furniture','decorate','','secondary')+btn('Buy a home','houses','','secondary'));}
function furnitureBuy(id){const owned=state.owned.includes(id);if(owned){const r=C.equip(state,id);if(!r.ok){toast(r.message);return}close();roomKey='';room();window.KittyRoom.decorate();render();return;}const r=C.buy(state,id);render();furnitureShop(furnitureCategory);toast(r.message);}
function houses(){sheet('Find a new home','YOUR GOLD · '+state.gold+' G','<div class="home-catalog">'+D.houses.map(h=>'<article class="product">'+modelThumb(h.model)+'<h3>'+h.name+'</h3><p>'+h.description+'</p>'+btn(state.house===h.id?'You live here':state.ownedHouses.includes(h.id)?'Move here':C.price(state,h)+' G · Buy & move','moveHouse',h.id,state.house===h.id?'secondary':'primary')+'</article>').join('')+'</div>');}
function moveHouse(id){const r=C.moveHouse(state,id);if(!r.ok){toast(r.message);return}close();roomKey='';room();render();toast(r.message);}
function puppies(id=state.breed||'corgi'){if(!['corgi','pug','shepherd','shiba'].includes(id))id=state.breed||'corgi';previewBreed=id;sheet('Meet the puppies','CHOOSE A LOOK · KEEP YOUR NAME AND PROGRESS','<div id="puppyPreview" class="puppy-preview"></div><div class="breed-row">'+[['corgi','Corgi'],['pug','Pug'],['shepherd','Shepherd'],['shiba','Shiba']].map(([k,n])=>btn(n,'puppies',k,k===id?'primary':'secondary')).join('')+'</div>'+btn('Choose this puppy','usePuppy'));window.KittyPreview.open($('#puppyPreview'),id);}
function usePuppy(){state.species='dog';state.breed=previewBreed;close();roomKey='';room();render();toast('Let’s make memories together!');}
function homeUpgrade(){const lv=state.homeLevel||0,cost=lv<2?[120,260][lv]*(C.redCount(state)>=2?2:1):0;sheet('A bigger home','HOME · LEVEL '+(lv+1),'<p>'+(lv===2?'Your home has two extensions.': 'Add real floor space for play and furniture.')+'</p>'+ (lv<2?btn('Build extension · '+cost+' G','buildHome'):'') );}
function buildHome(){const r=C.upgradeHome(state);if(!r.ok){toast(r.message);return}close();room();render();toast(r.message);}
function walk(){if(busy)return;close();$('#roomLayer').hidden=true;$('#game').classList.add('town-mode');window.KittyTown.open($('#townLayer'),{state,save:()=>{persist();render()},onHome:home,onTalk:(id,snapshot)=>{townBackdrop[id]=snapshot;home();if(D.locations.some(l=>l.id===id))place(id);else if(id==='shop')shop();else care();},onGame:id=>{home();minigame(id)},onShop:()=>{home();shop()},onFetch:()=>{home();play('ribbon')},speak,wrong:()=>S.wrong(state.sound)});}
function more(){sheet('More','DAY '+state.day+' · '+Math.max(0,3-state.actions)+' OUTINGS LEFT',btn('Arrange room','decorate','','secondary')+btn('Buy a home','houses','','secondary')+btn('Expand my home','homeUpgrade','','secondary')+btn('Meet the puppies','puppies','','secondary')+btn('Take a walk','walk','','secondary')+btn('Dress up','closet','','secondary')+btn('Memories','album','','secondary')+btn('Save / Load','saves','','secondary')+btn('Settings','settings','','secondary'));}
function decorate(){close();room();window.KittyRoom.decorate?.();}

function readSlots(){try{return JSON.parse(localStorage.getItem('little-lives-slots-v1')||'[]')}catch{return []}}
function saves(){const slots=readSlots();sheet('Save & Load','KEEP YOUR LITTLE FRIEND', '<p>Your progress saves automatically on this device.</p>'+[0,1,2].map(i=>{const v=slots[i];return '<article class="save-slot"><b>Slot '+(i+1)+'</b><p>'+(v?esc(v.state.name)+' · Day '+v.state.day+' · Lv. '+C.level(v.state)+' · '+v.state.gold+' G<br>'+esc(new Date(v.at).toLocaleString('ko-KR')):'Empty slot')+'</p><div>'+btn(v?'Replace save':'Save here','saveSlot',String(i),'secondary')+(v?btn('Load','loadSlot',String(i),'secondary'):'')+'</div></article>'}).join('')+btn('Download save file','exportSave','','secondary')+'<label class="secondary import-save">Import save file<input id="saveFile" type="file" accept=".json,application/json"></label><p class="fine">A save file lets you move your pet to another device. Loading keeps a backup of your previous progress.</p>'+(localStorage.getItem('little-lives-load-backup')?btn('Undo last load','undoLoad','','secondary'):''));$('#saveFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>2000000)throw Error();const raw=JSON.parse(await f.text());restoreSave(raw.state||raw);}catch{toast('This is not a valid Little Lives save file.')}};}
function validSave(raw){return raw&&raw.version===3&&typeof raw.name==='string'&&['cat','dog'].includes(raw.species)&&Number.isFinite(raw.gold)&&raw.gold>=0&&Number.isFinite(raw.xp)&&raw.xp>=0&&Number.isInteger(raw.day)&&raw.day>=1&&Array.isArray(raw.owned)&&Array.isArray(raw.memories)&&raw.memories.every(m=>m&&typeof m.id==='string'&&typeof m.name==='string'&&typeof m.title==='string'&&Array.isArray(m.photos)&&m.photos.every(p=>typeof p==='string'))&&Array.isArray(raw.claimed)&&raw.claimed.every(k=>typeof k==='string')&&(!raw.active||(D.episodes.some(e=>e.id===raw.active.episode&&Number.isInteger(raw.active.index)&&raw.active.index>=0&&raw.active.index<e.nodes.length)&&Array.isArray(raw.active.correct)&&raw.active.snapshot&&raw.active.choices));}
function restoreSave(raw){if(!validSave(raw)){toast('This is not a valid Little Lives save file.');return}try{const old=JSON.stringify(state),next=C.normalize(raw);localStorage.setItem('little-lives-load-backup',old);window.KittyRoom?.close();roomKey='';window.KittyArcade?.stop();state=next;persist();close();$('#adoption').hidden=state.adopted;render();if(!state.adopted)adoption();bubble('Welcome back, '+state.name+'!');toast('Progress loaded.');}catch{toast('Unable to load this save. Your current game is still here.');}}
function saveSlot(i){try{const slots=readSlots();slots[Number(i)]={at:new Date().toISOString(),state:JSON.parse(JSON.stringify(state))};localStorage.setItem('little-lives-slots-v1',JSON.stringify(slots));saves();toast('Progress saved.')}catch{toast('Storage is full. Download a save file instead.')}}
function exportSave(){const blob=new Blob([JSON.stringify({game:'Little Lives',at:new Date().toISOString(),state},null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='little-lives-day-'+state.day+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),10000);}
const commands={dailyTasks,growth,goOut:outing,furnitureShop,furnitureBuy,houses,moveHouse,puppies,usePuppy,starterBreed:id=>{updateStarter();starter.breed=id;adoption()},walk,homeUpgrade,buildHome,more,decorate,settings,room,saves,saveSlot,loadSlot:i=>{const slot=readSlots()[Number(i)];if(slot)restoreSave(slot.state)},exportSave,undoLoad:()=>{try{restoreSave(JSON.parse(localStorage.getItem('little-lives-load-backup')))}catch{toast('No backup found.')}},arcade,minigame,rest:()=>sheet('Time for a good sleep','RESTORE ENERGY',btn('Sleep & next day','sleep')),clinic:()=>place('clinic'),species:a=>{updateStarter();if(starter.name==='Tori'||starter.name==='Momo')starter.name=a==='cat'?'Tori':'Momo';starter.species=a;adoption()},starter:a=>{updateStarter();starter.outfit=a;adoption()},adopt,care,pantry,feed,toys,pet,play,sleep,shop,buy,equip,closet,wish:id=>{state.goal=id;render();toast('A lovely goal. Let’s earn it together.')},place,begin,resume:()=>{close();story()},answer:a=>answer(Number(a)),home:()=>{close();home()},memory,album,legacy,movie,notebook,read:speak,leave:()=>{C.leave(state);close();home()},sound:()=>{state.sound=!state.sound;persist();settings()},hints:()=>{state.hints=!state.hints;persist();settings()}};
document.addEventListener('click',e=>{const b=e.target.closest('[data-cmd]');if(b&&!b.disabled){const f=commands[b.dataset.cmd];if(f)f(b.dataset.arg)}});
$$('[data-nav]').forEach(b=>b.onclick=()=>({care,shop,closet,more,out:outing,album}[b.dataset.nav])());$$('[data-icon]').forEach(el=>el.innerHTML=icon(el.dataset.icon));
$('#settings').innerHTML=icon('gear');$('#listen').innerHTML=icon('volume');$('#settings').onclick=settings;$('#profile').onclick=()=>growth();$('#levelButton').onclick=()=>growth();$('#scoreButton').onclick=()=>growth();$('#goal').onclick=()=>shop(D.goods.find(g=>g.id===state.goal)?.type||'furniture');$('#sheetClose').onclick=close;$('#petHit').onclick=pet;$('#sleep').onclick=sleep;$('#toyTarget').onclick=catchToy;$('#endPlay').onclick=()=>$('#playLayer').hidden=true;$('#episodeBack').onclick=pause;$('#listen').onclick=()=>{const c=C.current(state);if(c)speak(C.expand(state,c.node.line))};$('#hintButton').onclick=()=>{const c=C.current(state);if(!c)return;$('#hint').hidden=!$('#hint').hidden;if(!$('#hint').hidden)speak(C.expand(state,c.node.choices.find(x=>x.ok).text))};$('#nextLine').onclick=next;
document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(!$('#episode').hidden)pause();else close();$('#playLayer').hidden=true}});
setInterval(()=>{if(!state.adopted||document.hidden||busy||!$('#sheetLayer').hidden||!$('#playLayer').hidden)return;C.careTick(state);render();},45000);
render();if(!state.adopted)adoption();else home();
})();
