(function(root,factory){if(typeof module==='object'&&module.exports)module.exports=factory(require('./expansion.js')(require('./data.js')));else root.KittyCore=factory(root.KittyData)})(typeof globalThis!=='undefined'?globalThis:this,(D)=>{
const clamp=n=>Math.max(0,Math.min(100,Number(n)||0));
const init=()=>({version:3,breed:'corgi',house:'studio',ownedHouses:['studio'],storedItems:[],houseLayouts:{},houseLevels:{},homeLevel:0,adopted:false,species:'cat',name:'Tori',day:1,actions:0,xp:0,score:0,gold:45,food:65,energy:85,stress:15,health:100,bond:0,skills:{kindness:0,confidence:0},outfit:'mint',owned:['mint','rain'],pantry:{kibble:3,soup:1},decor:{},goal:'bed',fedToday:0,playedToday:0,pettedToday:false,careClaimed:false,memories:[],claimed:[],mastery:{},review:{},active:null,sound:true,hints:true,voice:'',legacyMovies:[],milestones:[],log:[]});
function normalize(raw){const base=init();if(!raw||raw.version!==3)return base;const s={...base,...raw};s.skills={...base.skills,...raw.skills};s.pantry={...raw.pantry};s.decor={...raw.decor};s.owned=Array.from(new Set([...base.owned,...(Array.isArray(raw.owned)?raw.owned:[])]));for(const k of ['food','energy','stress','health'])s[k]=clamp(s[k]);s.day=Math.max(1,Math.floor(s.day)||1);s.name=cleanName(s.name)||'Tori';s.species=['dog','fox','duck'].includes(s.species)?s.species:'cat';s.breed=D.pets.some(p=>p.id===s.breed&&p.species===s.species)?s.breed:(D.pets.find(p=>p.species===s.species)?.id||'cat');s.house=D.houses.some(h=>h.id===s.house)?s.house:'studio';s.ownedHouses=[...new Set(['studio',...(Array.isArray(s.ownedHouses)?s.ownedHouses:[])])].filter(id=>D.houses.some(h=>h.id===id));if(!s.ownedHouses.includes(s.house))s.house='studio';s.storedItems=(Array.isArray(s.storedItems)?s.storedItems:[]).filter(id=>s.owned.includes(id));s.houseLayouts=s.houseLayouts&&typeof s.houseLayouts==='object'?s.houseLayouts:{};s.houseLevels=s.houseLevels&&typeof s.houseLevels==='object'?s.houseLevels:{};s.homeLevel=Math.min(2,Math.max(0,Math.floor(Number(s.homeLevel)||0)));s.roomLayout=Object.fromEntries(Object.entries(raw.roomLayout||{}).filter(([id,p])=>(D.goods.some(g=>g.id===id&&g.model)||['bed','quilt','ball','wand'].includes(id))&&p&&Number.isFinite(p.x)&&p.x>=-3.8&&p.x<=12.8&&Number.isFinite(p.z)&&p.z>=-11.2&&p.z<=3.3+s.homeLevel*1.6&&Number.isFinite(p.r)));if(!D.goods.some(g=>g.id===s.outfit&&g.type==='outfit'))s.outfit='mint';return s;}
const cleanName=name=>String(name||'').replace(/[<>&"'\n\r]/g,'').trim().slice(0,18);
const level=s=>1+Math.floor(s.xp/80);
const age=s=>3+Math.floor((s.day-1)/3);
const ageStage=s=>age(s)<6?0:age(s)<12?1:2;
const stageName=s=>['Little one','Growing up','Young adult'][ageStage(s)];
function adopt(s,species,name,outfit){if(s.adopted)return {ok:false,message:'Your friend is already home.'};const n=cleanName(name);if(!n)return {ok:false,message:'Please give your friend a name.'};s.species=['dog','fox','duck'].includes(species)?species:'cat';s.name=n;s.outfit=outfit==='rain'?'rain':'mint';s.adopted=true;return {ok:true};}
function pet(s){s.stress=clamp(s.stress-3);if(!s.pettedToday){s.pettedToday=true;s.bond+=1;s.score+=2}return {ok:true,message:'I like being with you.'};}
const redCount=s=>[s.food,s.energy,100-s.stress,s.health].filter(v=>v<40).length;
const price=(s,g)=>g.price*(redCount(s)>=2?2:1);
function careTick(s){s.food=clamp(s.food-5);s.energy=clamp(s.energy-5);s.stress=clamp(s.stress+4);if(redCount(s)>=2)s.health=clamp(s.health-3);}
function buy(s,id){const g=D.goods.find(x=>x.id===id);if(!g)return {ok:false,message:'That item is not available.'};if(g.type!=='food'&&s.owned.includes(id))return {ok:false,message:'You already own this.'};const cost=price(s,g);if(s.gold<cost)return {ok:false,message:'You need '+(cost-s.gold)+' more G.'};s.gold-=cost;if(g.type==='food')s.pantry[id]=(s.pantry[id]||0)+1;else {s.owned.push(id);if(g.model)s.storedItems.push(id);}return {ok:true,message:g.name+' is yours!'};}
function upgradeHome(s){const level=s.homeLevel||0;if(level>=2)return {ok:false,message:'Your home is fully expanded.'};const cost=[120,260][level]*(redCount(s)>=2?2:1);if(s.gold<cost)return {ok:false,message:'You need '+(cost-s.gold)+' more G.'};s.gold-=cost;s.homeLevel=level+1;return {ok:true,message:'Your home is bigger!'};}
function moveHouse(s,id){const h=D.houses.find(h=>h.id===id);if(!h)return {ok:false,message:'Choose an available home.'};if(s.house===id)return {ok:false,message:'You already live here.'};const owned=s.ownedHouses.includes(id),cost=owned?0:price(s,h);if(s.gold<cost)return {ok:false,message:'You need '+(cost-s.gold)+' more G.'};s.gold-=cost;if(!owned)s.ownedHouses.push(id);s.houseLayouts[s.house]=JSON.parse(JSON.stringify(s.roomLayout||{}));s.houseLevels[s.house]=s.homeLevel;s.house=id;s.homeLevel=s.houseLevels[id]??h.level;s.roomLayout=s.houseLayouts[id]||{};return {ok:true,message:'Welcome to '+h.name+'!'};}
function equip(s,id){const g=D.goods.find(x=>x.id===id);if(!g||!s.owned.includes(id))return {ok:false,message:'Buy this item first.'};if(g.type==='outfit')s.outfit=id;else if(g.type==='furniture'){s.decor[g.slot]=id;s.storedItems=s.storedItems.filter(x=>x!==id);}else return {ok:false,message:'Use this item in care.'};return {ok:true,message:'All ready!'};}
function feed(s,id){const g=D.goods.find(x=>x.id===id&&x.type==='food');if(!g||!s.pantry[id])return {ok:false,message:'Your bowl is empty. Visit the shop.'};if(s.food>=95)return {ok:false,message:'I am full. Save it for later.'};s.pantry[id]--;s.food=clamp(s.food+g.food);s.stress=clamp(s.stress+g.stress);s.fedToday++;if(s.fedToday===1){s.bond+=2;s.score+=4}return {ok:true,message:id==='fish'?'My favorite! Thank you!':'Yum! That was lovely.'};}
function play(s,id){if(s.energy<10)return {ok:false,message:'I am sleepy. Let’s rest first.'};const g=D.goods.find(x=>x.id===id&&x.type==='toy');if(id!=='ribbon'&&(!g||!s.owned.includes(id)))return {ok:false,message:'Choose a toy you own.'};s.stress=clamp(s.stress-(g?.relief||14));s.energy=clamp(s.energy-8);s.playedToday++;if(s.playedToday===1){s.bond+=3;s.score+=4}return {ok:true,message:'That was fun!'};}
function careBonus(s){if(s.careClaimed||!s.fedToday||!s.playedToday||!s.pettedToday)return false;s.careClaimed=true;s.score+=10;s.bond+=2;return true;}
function sleep(s){if(s.active)return {ok:false,message:'Finish or leave your outing first.'};const before=ageStage(s);s.day++;s.actions=0;s.food=clamp(Math.max(25,s.food-18));s.energy=s.decor.bed?100:85;s.stress=clamp(s.stress-(s.decor.quilt?35:22)-(s.decor.room?8:0));s.health=clamp(s.health+5);s.fedToday=0;s.playedToday=0;s.pettedToday=false;s.careClaimed=false;s.pantry.kibble=Math.max(2,s.pantry.kibble||0);return {ok:true,grew:before!==ageStage(s),message:'Good morning! A new day begins.'};}
function illness(s){if((s.tummyEventDay===s.day||(s.day%3===2&&s.actions===1))&&s.checkupDay!==s.day)return {symptom:'a sore tummy',feverAnswer:'No, my pet has no fever.',feverStatus:'no fever'};if(s.checkupDay===s.day)return {symptom:'a little tiredness',feverAnswer:'No, my pet has no fever.',feverStatus:'no fever'};if(s.health<70||s.day%4===0)return {symptom:'a cough',feverAnswer:'Yes, my pet has a fever.',feverStatus:'a mild fever'};if(s.food<35)return {symptom:'a sore tummy',feverAnswer:'No, my pet has no fever.',feverStatus:'no fever'};return {symptom:'a little tiredness',feverAnswer:'No, my pet has no fever.',feverStatus:'no fever'};}
function mission(s){if(s.active){const e=D.episodes.find(e=>e.id===s.active.episode);if(e)return {location:e.location,title:'진행 중 · '+e.title};}if(s.checkupDay!==s.day&&(s.health<65||(s.tummyEventDay===s.day||(s.day%3===2&&s.actions===1))))return {location:'clinic',title:'배가 아파 보여요 · 동물병원에 가요',urgent:true};if(s.actions===0)return {location:'school',title:'아침 등원 · 유치원에 가요'};if(s.actions===1){const places=[['library','오후 일과 · 도서관에서 책을 빌려요'],['cafe','오후 휴식 · 카페에서 쉬어 가요'],['shop','오후 심부름 · 상점에 들러요']];const [location,title]=places[(s.day-1)%3];return {location,title};}return {location:'home',title:'오늘의 일과 끝 · 집에서 쉬어요'};}
function chooseVisit(s,location){if(location==='clinic'&&mission(s).urgent)return D.episodes.find(e=>e.id==='clinic-checkup');const list=D.episodes.filter(e=>e.location===location&&e.level<=level(s)&&e.id!=='school-sports'&&e.id!=='cafe-shift');if(!list.length)return null;const last=s.lastVisits?.[location],start=(list.findIndex(e=>e.id===last)+1)%list.length,ordered=[...list.slice(start),...list.slice(0,start)];return ordered.find(e=>e.id!==last&&!s.claimed.includes(s.day+':'+e.id))||ordered.find(e=>e.id!==last)||ordered[0];}
function begin(s,id){if(s.active)return {ok:false,message:'Your current story is waiting.'};const e=D.episodes.find(x=>x.id===id);if(!e)return {ok:false,message:'No story here yet.'};if(level(s)<e.level)return {ok:false,message:'Reach level '+e.level+' first.'};if(s.actions>=3)return {ok:false,message:'A full day! Let’s go home and sleep.'};if(s.energy<15&&e.location!=='clinic')return {ok:false,message:'I am tired. Let’s sleep first.'};s.lastVisits={...(s.lastVisits||{}),[e.location]:e.id};const health=illness(s);s.active={episode:id,index:0,choices:{},correct:[],mistakes:0,needsRetry:false,accepted:false,startedDay:s.day,snapshot:{...health,age:age(s),eatenAnswer:s.fedToday?'Yes, my pet has eaten.':'No, my pet has not eaten yet.',foodStatus:s.fedToday?'has eaten today':'has not eaten today'},result:null};return {ok:true};}
function expand(s,text){const a=s.active;const values={cat:s.name,age:age(s),...(a?.snapshot||{}),...(a?.choices||{})};return String(text).replace(/\bcat\b(?!\})/g,s.species||'cat').replace(/\{([^}]+)\}/g,(_,key)=>values[key]??'your friend');}
function current(s){if(!s.active)return null;const episode=D.episodes.find(x=>x.id===s.active.episode);return {episode,node:episode.nodes[s.active.index]};}
function answer(s,index){const c=current(s);if(!c||s.active.accepted)return {ok:false,message:'Continue to the next scene.'};const choice=c.node.choices[index];if(!choice)return {ok:false};if(!choice.ok){s.active.mistakes++;s.active.needsRetry=true;s.review[c.node.id]={text:expand(s,c.node.choices.find(x=>x.ok).text),due:s.day+1};if(c.episode.battle&&s.active.mistakes>=6){s.energy=clamp(s.energy-10);s.stress=clamp(s.stress+8);s.active=null;return {ok:false,retreat:true,message:'Let’s rest and try again. No gold was lost.'}}return {ok:false,retry:true,message:'Listen once, then try again.'};}s.active.accepted=true;s.active.choices[c.node.id]=choice.value||expand(s,choice.text);s.active.correct.push({id:c.node.id,helped:s.active.needsRetry,text:expand(s,choice.text)});return {ok:true,message:expand(s,choice.text)};}
function next(s){const c=current(s);if(!c||!s.active.accepted)return {ok:false};if(s.active.index<c.episode.nodes.length-1){s.active.index++;s.active.accepted=false;s.active.needsRetry=false;return {ok:true,finished:false}}return finish(s);}
function finish(s){const c=current(s);if(!c)return {ok:false};const a=s.active,e=c.episode,claim=a.startedDay+':'+e.id;if(s.claimed.includes(claim)){s.active=null;return {ok:true,finished:true,xp:0,gold:0,score:0,replay:true,episode:e.id};}
let xp=40,score=25;for(const turn of a.correct){xp+=turn.helped?6:10;score+=turn.helped?3:5;s.mastery[turn.id]=(s.mastery[turn.id]||0)+(turn.helped?0:1);if(!turn.helped)delete s.review[turn.id];}
const before=level(s);s.xp+=xp;s.score+=score;const earnedMilestones=[100,250,500].filter(n=>s.score>=n&&!s.milestones.includes(n));const bonus=earnedMilestones.reduce((sum,n)=>sum+(n===100?20:n===250?40:60),0);s.milestones.push(...earnedMilestones);const firstClear=!s.memories.some(m=>m.episode===e.id);const firstBonus=firstClear?150:0;s.gold+=e.reward+bonus+firstBonus;if(firstClear){s.pantry.soup=(s.pantry.soup||0)+2;s.pantry.treat=(s.pantry.treat||0)+2;}s.bond+=4;s.skills[e.skill]+=3;s.actions++;if(s.day%3===2&&s.actions===1)s.tummyEventDay=s.day;s.energy=clamp(s.energy-22);s.food=clamp(s.food-18);s.stress=clamp(s.stress+12);if(e.effect==='meal'){s.food=clamp(s.food+40);s.stress=clamp(s.stress-12)}if(e.effect==='care'){s.checkupDay=s.day;s.health=100;s.stress=clamp(s.stress-15)}if(e.effect==='rest'){s.energy=100;s.stress=clamp(s.stress-20)}s.claimed.push(claim);
const memory={id:e.id+'-'+a.startedDay,episode:e.id,location:e.location,day:a.startedDay,age:a.snapshot.age,name:s.name,species:s.species,choices:{...a.choices},title:e.title,photos:D.photos[e.location],caption:expand(s,e.ending)};s.memories.push(memory);s.active=null;return {ok:true,finished:true,xp,gold:e.reward+bonus+firstBonus,bonus,firstBonus,supplies:firstClear,earnedMilestones,score,levelUp:level(s)>before,episode:e.id,memory};}
function discover(s,location){const d=D.discoveries[location];if(!d)return {ok:false};const key='discovery:'+s.day+':'+location;if(s.claimed.includes(key))return {ok:false,replay:true,message:'오늘은 이미 찾았어요. 내일 다시 찾아봐요.'};s.claimed.push(key);s.gold+=d.gold;s.xp+=d.xp;return {ok:true,...d};}
function leave(s){s.active=null;return {ok:true};}
return {discover,mission,chooseVisit,upgradeHome,moveHouse,redCount,price,careTick,init,normalize,cleanName,level,age,ageStage,stageName,adopt,pet,buy,equip,feed,play,careBonus,sleep,illness,begin,expand,current,answer,next,leave};
});
