/* The learning voice is generated audio, identical across devices. No system-TTS fallback. */
(()=>{'use strict';const S=window.KittySpeech,oldStop=S.stop;let context=null,source=null,complete=null,serial=0;const memory=new Map(),pending=new Map();
const clean=t=>String(t).normalize('NFC').replace(/[’‘]/g,"'").replace(/\s+/g,' ').trim();
async function bytes(text){text=clean(text);if(memory.has(text))return memory.get(text);if(pending.has(text))return pending.get(text);const job=(async()=>{let cache,key;try{const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));const hash=Array.from(new Uint8Array(digest),x=>x.toString(16).padStart(2,'0')).join('');key=new URL('assets/animal-town/voice-cache-v1/'+hash,location.href).href;cache=await caches.open('kitty-natural-voice-v1');const stored=await cache.match(key);if(stored)return await stored.arrayBuffer()}catch{}const fixed=window.KittyVoiceFiles?.[text];let r;if(fixed)r=await fetch(new URL(fixed,document.baseURI));else r=await fetch('/api/kitty-speech',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text}),signal:AbortSignal.timeout(30000)});if(!r.ok)throw Error('audio unavailable');const data=await r.arrayBuffer();try{if(cache&&key)await cache.put(key,new Response(data,{headers:{'Content-Type':'audio/mpeg'}}))}catch{}return data})();pending.set(text,job);try{const data=await job;if(memory.size>100)memory.delete(memory.keys().next().value);memory.set(text,data);return data}finally{pending.delete(text)}}
S.stop=()=>{serial++;oldStop();if(complete)complete('cancelled');if(source){source.onended=null;try{source.stop()}catch{}source.disconnect();source=null}};
S.speak=(text,{enabled=true}={})=>{S.stop();if(!enabled)return Promise.resolve('unavailable');const id=serial;try{const AC=window.AudioContext||window.webkitAudioContext;if(!AC)return Promise.resolve('unavailable');context=context||new AC();const resumed=context.resume();return new Promise(resolve=>{let done=false;const finish=status=>{if(done)return;done=true;if(complete===finish)complete=null;resolve(status)};complete=finish;(async()=>{await resumed;const data=await bytes(text);if(id!==serial)return finish('cancelled');const buffer=await context.decodeAudioData(data.slice(0));if(id!==serial)return finish('cancelled');const playing=context.createBufferSource();playing.buffer=buffer;playing.playbackRate.value=1;playing.connect(context.destination);source=playing;playing.onended=()=>{playing.disconnect();if(source===playing)source=null;finish('ended')};playing.start();})().catch(()=>finish('error'))})}catch{return Promise.resolve('error')}};
S.prepare=text=>bytes(text).catch(()=>null);
S.engine='natural-american';
})();
