import * as T from 'three';
import {asset} from './world-assets.js';
import {attachPet} from './pet-model.js';
let stop=()=>{};
const places=[
 {id:'home',name:'Home',x:-6,z:5,color:'#dca477'},
 {id:'shop',name:'Sunny Shop',x:-6,z:-3,color:'#e9be70'},
 {id:'library',name:'Library',x:6,z:-3,color:'#95afb5'},
 {id:'airport',name:'Airport',x:6,z:-11,color:'#c5d8d9'},
 {id:'cafe',name:'Paws Cafe',x:6,z:5,color:'#dca69b'},
 {id:'school',name:'강아지·고양이 유치원',x:-6,z:-11,color:'#abc59a'},
 {id:'hotel',name:'달빛 호텔',x:-6,z:-19,color:'#d9b1ca'},
 {id:'clinic',name:'햇살 동물병원',x:6,z:-19,color:'#acd8cf'},
 {id:'forest',name:'모험의 숲',x:0,z:-27,color:'#91b3a2'},
 {id:'park',name:'Play Park',x:0,z:11,color:'#91b3a2'}
];
const stories={
 shop:[['Apple basket','Find three apples.','사과 3개를 찾아보세요.',['Apple','Banana','Milk'],0],['Toy shelf','Which toy can roll?','어떤 장난감이 굴러갈까요?',['A ball.','A book.','A hat.'],0],['Cash register','How would you like to pay?','어떻게 계산하시겠어요?',['With coins, please.','I am sleeping.','It is raining.'],0]],
 library:[['Story book','May I borrow this book?','이 책을 빌려도 될까요?',['Yes. Here you are.','At Gate Two.','Chicken, please.'],0],['Book shelf','Put the blue book on the shelf.','파란 책을 책장에 놓으세요.',['The blue book.','The red ball.','The yellow bag.'],0],['Reading desk','Let’s match words together.','함께 단어의 짝을 맞춰 봐요.',['Let’s play!','I need a ticket.','My soup is hot.'],0]],
 airport:[['Suitcase','What goes in your travel bag?','여행 가방에 무엇을 넣을까요?',['My clothes.','A big tree.','A sofa.'],0],['Passport desk','May I see your passport?','여권을 보여주시겠어요?',['Here is my passport.','Here is my soup.','I am a book.'],0],['Departure gate','Are you ready to fly?','비행할 준비가 되었나요?',['Yes, let’s go!','It is a spoon.','The book is red.'],0]],
 cafe:[['Kitchen','Add chicken to the sandwich.','샌드위치에 닭고기를 넣으세요.',['Chicken goes here.','My passport is here.','This is a bed.'],0],['Water jug','Would you like some water?','물을 좀 드릴까요?',['Yes, water, please.','I am a window.','At the airport.'],0],['Table','Your food is ready.','음식이 준비되었어요.',['Thank you!','Where is Gate Two?','Good night, book.'],0]],
 school:[['Blocks','Which block is red?','어느 블록이 빨간색인가요?',['This red block.','This blue book.','This yellow bag.'],0],['School bag','What is your friend’s name?','친구의 이름은 무엇인가요?',['My friend is {name}.','My friend is a ticket.','My friend is a spoon.'],0],['Art desk','Let’s play a word game.','단어 게임을 해 봐요.',['That sounds fun!','Here is the bill.','It is a passport.'],0]],
 park:[['Ball','Can you catch the ball?','공을 잡을 수 있나요?',['Yes, I can!','I am a book.','A table for two.'],0],['Picnic basket','Are you hungry?','배가 고픈가요?',['Yes. A snack, please.','Yes. I am a tree.','At Gate Two.'],0],['Flower bed','Please be gentle with the flowers.','꽃을 조심히 다뤄 주세요.',['Okay. I will be gentle.','Give me a passport.','Two tickets, please.'],0]]
};
export function openTown(host,{state,destination,save,onHome,onTalk,onGame,onShop,onFetch,speak,wrong}){
 places.forEach(p=>p.name=window.KittyI18n?.t(p.name)||p.name);stop();let alive=true,frame=0,last=0,inside=null,pending=null,arrived=false,locked=false,activityId=0,npcRig=null,npcPending=false,sportMotion=null,sportBall=null,sportArena=false,sportPhotos=[];host.hidden=false;
 host.innerHTML='<header class="town-head"><button id="townBack">Home</button><b id="townTitle">A walk together</b><button id="townSports" hidden>운동장</button><button id="townTalk" hidden>Talk</button></header><div class="town-canvas"></div><nav class="town-stops"></nav><div class="town-activity" hidden></div><div class="town-tip" role="status">Tap the path to walk. Tap a building to visit.</div>';
 const C=window.KittyCore,D=window.KittyData;
 const $=q=>host.querySelector(q),tip=t=>$('.town-tip').textContent=t;
 const scene=new T.Scene();scene.background=new T.Color('#c8ddcb');scene.fog=new T.Fog('#c8ddcb',28,65);let renderer;
 try{renderer=new T.WebGLRenderer({antialias:true});}catch{$('.town-tip').textContent='3D is unavailable on this device.';$('#townBack').onclick=onHome;return;}
 renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.1;$('.town-canvas').append(renderer.domElement);
 const camera=new T.PerspectiveCamera(45,1,.1,90),sun=new T.DirectionalLight('#fff0cd',3);sun.position.set(-5,15,7);sun.castShadow=true;sun.shadow.normalBias=.035;sun.shadow.bias=-.00015;sun.shadow.mapSize.set(1024,1024);Object.assign(sun.shadow.camera,{left:-18,right:18,top:18,bottom:-18});scene.add(sun,new T.HemisphereLight('#fff9e9','#9ab28f',2.2));
 const outside=new T.Group(),interior=new T.Group();scene.add(outside,interior);interior.visible=false;
 const mat=c=>new T.MeshStandardMaterial({color:c,roughness:.88});
 function box(w,h,d,c,x,y,z,parent=outside){const m=new T.Mesh(new T.BoxGeometry(w,h,d),mat(c));m.position.set(x,y,z);m.castShadow=m.receiveShadow=true;parent.add(m);return m;}
 function orb(r,c,x,y,z,parent=outside){const m=new T.Mesh(new T.SphereGeometry(r,20,12),mat(c));m.position.set(x,y,z);m.castShadow=true;parent.add(m);return m;}
 function label(text,x,y,z,parent=outside){text=window.KittyI18n?.t(text)||text;const c=document.createElement('canvas');c.width=512;c.height=96;const g=c.getContext('2d');g.fillStyle='#fff5df';g.beginPath();g.roundRect(2,2,508,92,22);g.fill();g.fillStyle='#594635';g.font='bold 37px system-ui';g.textAlign='center';g.fillText(text,256,61);const texture=new T.CanvasTexture(c);texture.colorSpace=T.SRGBColorSpace;const s=new T.Sprite(new T.SpriteMaterial({map:texture,depthTest:false}));s.position.set(x,y,z);s.scale.set(3.5,.66,1);parent.add(s);return s;}
 const ground=box(27,.15,46,'#a4bf90',0,-.12,-7);ground.userData.ground=true;box(3,.025,44,'#dbcbad',0,0,-7);for(const z of [-24,-16,-8,0,8])box(22,.03,2,'#dbcbad',0,.01,z);
 for(const p of places){const g=new T.Group();g.position.set(p.x,0,p.z);g.userData.place=p.id;outside.add(g);if(p.id==='park'){box(4,.1,3,'#87b291',0,.05,0,g);for(const x of [-1.5,1.5])box(.12,1.6,.12,'#e8bd75',x,.8,0,g);box(3.1,.12,.12,'#e8bd75',0,1.6,0,g);box(1.1,.1,.65,'#d39171',0,.55,0,g);label(p.name,0,2.4,0,g);p.door={x:p.x,z:p.z-2.5};continue;}box(3.8,2.6,3.2,p.color,0,1.3,0,g);const roof=new T.Mesh(new T.ConeGeometry(3.05,1.1,4),mat('#688f84'));roof.rotation.y=Math.PI/4;roof.position.y=3.12;g.add(roof);box(.8,1.5,.1,'#825a3d',0,.76,1.66,g);for(const x of [-1.25,1.25])box(.65,.8,.12,'#d9eff0',x,1.6,1.65,g);label(p.name,0,4.1,0,g);p.door={x:p.x,z:p.z+2.5};}
 const buildingModels={home:state.house==='villa'?'building-type-q':state.house==='cottage'?'building-type-k':'building-type-f',shop:'building-a',library:'building-e',airport:'building-j',cafe:'building-b',school:'building-type-b',hotel:'building-type-q',clinic:'building-type-c',forest:'building-type-k'};
 for(const g of [...outside.children]){const id=g.userData.place;if(!id||id==='park')continue;const old=[...g.children];asset(buildingModels[id],g,{width:4.4,alive:()=>alive,onReady:h=>{old.forEach(o=>{if(!o.isSprite){g.remove(o);o.geometry?.dispose();o.material?.dispose();}});old.filter(o=>o.isSprite).forEach(o=>o.position.y=new T.Box3().setFromObject(h).max.y-g.position.y+.5);host.dataset.worldAssets='ready';}});}
 for(let i=0;i<24;i++){const x=(i%2?1:-1)*(10.6+Math.sin(i)*.5),z=-13+(i/24)*27;asset(i%3?'tree_oak':'tree_simple',outside,{width:2+(i%3)*.3,x,z,alive:()=>alive});}
 for(const p of places.filter(p=>p.id!=='park')){for(const dx of [-2.8,2.8]){asset('planter',outside,{width:.65,x:p.x+dx,z:p.z+1.5,alive:()=>alive});asset('flower_redA',outside,{width:.48,x:p.x+dx,y:.35,z:p.z+1.5,alive:()=>alive});}asset('bench',outside,{width:1.6,x:p.x-2.8,z:p.z-.5,rotation:Math.PI/2,alive:()=>alive});for(let i=0;i<3;i++)asset('plant_bush',outside,{width:.85,x:p.x-1.4+i*1.4,z:p.z-2.6,alive:()=>alive});}
 for(let i=0;i<6;i++)asset('fence-low',outside,{width:1.6,x:-4.7+i*1.9,z:13.7,alive:()=>alive});asset('bench',outside,{width:2,x:3,z:11,rotation:-Math.PI/2,alive:()=>alive});asset('flower_redA',outside,{width:1,x:-3,z:11,alive:()=>alive});
 // A small plane makes the airport recognizable from the street.
 const plane=new T.Group();outside.add(plane);plane.position.set(7,.6,-15);box(.8,.55,3.2,'#faf2dc',0,0,0,plane);box(3.7,.15,.8,'#f9efd9',0,0,.2,plane);box(1.5,.12,.5,'#dcaa76',0,.3,-1.2,plane);
 const pet=new T.Group();scene.add(pet);const fallback=orb(.5,'#dca66d',0,.7,0,pet);fallback.scale.set(1,1,1.3);const rig=attachPet(pet,state,()=>alive);pet.position.set(0,0,7);let path=[],look=new T.Vector3(0,.5,7);const ray=new T.Raycaster(),pointer=new T.Vector2();
 const guardian=new T.Group();guardian.scale.setScalar(1.25);guardian.position.set(-1,0,7.8);scene.add(guardian);const guardianRig=attachPet(guardian,{species:'dog',breed:'walker',outfit:'mint'},()=>alive);
 const leashGeometry=new T.BufferGeometry().setFromPoints([new T.Vector3(),new T.Vector3(),new T.Vector3()]);const leash=new T.Line(leashGeometry,new T.LineBasicMaterial({color:'#c27f61'}));scene.add(leash);
 function obstacle(x,z){return places.filter(p=>p.id!=='park').some(p=>Math.abs(x-p.x)<2.3&&Math.abs(z-p.z)<2.05)}
 function navigate(x,z,visit=null){if(inside){path=[{x:Math.max(-3.4,Math.min(3.4,x)),z:Math.max(-2.5,Math.min(2.5,z))}];return;}const start=[Math.round(pet.position.x),Math.round(pet.position.z)],end=[Math.round(x),Math.round(z)],key=(x,z)=>x+','+z,q=[start],prev=new Map([[key(...start),null]]);let found=false;
  for(let i=0;i<q.length;i++){const [a,b]=q[i];if(a===end[0]&&b===end[1]){found=true;break}for(const [dx,dz]of [[1,0],[-1,0],[0,1],[0,-1]]){const xx=a+dx,zz=b+dz,k=key(xx,zz);if(Math.abs(xx)>12||zz< -29||zz>15||obstacle(xx,zz)||prev.has(k))continue;prev.set(k,[a,b]);q.push([xx,zz]);}}
  if(!found){tip('Choose a spot on the path.');return}let at=end,result=[];while(at){result.push({x:at[0],z:at[1]});at=prev.get(key(...at))}path=result.reverse().slice(1);pending=visit;arrived=false;if(visit)tip('Walking to '+places.find(p=>p.id===visit).name+'…');
 }
 function reward(key){const id='town:'+state.day+':'+key;if(state.claimed.includes(id))return 'Good practice!';state.claimed.push(id);state.gold+=8;state.xp+=12;state.score+=5;save();return '+8 G · +12 XP';}
 function activity(index){if(locked)return;const token=++activityId;const data=stories[inside][index],panel=$('.town-activity');panel.hidden=false;panel.innerHTML='<button class="town-dismiss">×</button><h3></h3><button class="town-hear">Listen</button><button class="town-translate">해석 보기</button><p class="town-ko" hidden></p><div class="town-answers"></div><p class="town-feedback" role="status"></p>';panel.querySelector('h3').textContent=data[1];panel.querySelector('.town-ko').textContent=data[2];panel.querySelector('.town-translate').onclick=()=>panel.querySelector('.town-ko').hidden=!panel.querySelector('.town-ko').hidden;panel.querySelector('.town-hear').onclick=()=>speak(data[1]);panel.querySelector('.town-dismiss').onclick=()=>{panel.hidden=true;locked=false;activityId++;};speak(data[1]);
  const order=[0,1,2].sort(()=>Math.random()-.5);for(const i of order){const b=document.createElement('button');b.textContent=data[3][i].replace('{name}',state.name);panel.querySelector('.town-answers').append(b);b.onclick=async()=>{if(locked)return;locked=true;b.classList.add(i===data[4]?'right':'wrong');if(i!==data[4]){wrong();panel.querySelector('.town-feedback').textContent='Listen and try again.';await speak(data[3][data[4]].replace('{name}',state.name));locked=false;return;}await speak(b.textContent);if(!alive||panel.hidden||token!==activityId)return;const location=inside;panel.querySelector('.town-feedback').textContent=reward(location+':'+index);const next=document.createElement('button');next.className='primary';next.textContent='Let’s do it!';panel.append(next);next.onclick=()=>{panel.hidden=true;locked=false;
   if(location==='shop'&&index===2){onShop();return;}if(location==='library'&&index===2||location==='school'&&index===2){onGame('pairs');return;}if(location==='airport'&&index===2){onGame('plane');return;}if(location==='park'&&index===0){onFetch();return;}
   if(location==='shop'&&index===0||location==='cafe'&&index===0||location==='library'&&index===1){collect(location);return;}
   tip(location==='airport'?'Passport checked. You are ready to travel.':location==='park'?'A lovely moment together.':location==='cafe'?'Served with a smile!':'A new memory together.');};};}
 }
 let collectMode=null,collectMeshes=[];
 function collect(location){for(const m of collectMeshes){if(m.parent){m.removeFromParent();m.geometry.dispose();m.material.dispose();}}collectMeshes=[];collectMode={location,count:0};tip(location==='library'?'Tap the 3 blue books.':location==='shop'?'Tap the 3 apples for your basket.':'Tap chicken, bread, and lettuce to serve lunch.');for(let i=0;i<3;i++){const m=location==='library'?box(.4,.1,.6,'#689bcd',-1.5+i*1.5,.4,1.4,interior):orb(.24,['#d96752','#e8b46c','#8fad65'][location==='shop'?0:i],-1.5+i*1.5,.4,1.4,interior);m.userData.collect=true;collectMeshes.push(m);}}
 function enter(id){if(id==='home'){onHome();return}inside=id;host.dataset.inside=id;npcPending=false;sportArena=false;outside.visible=false;interior.traverse(o=>{o.geometry?.dispose();for(const m of [].concat(o.material||[])){m.map?.dispose();m.dispose();}});interior.clear();interior.visible=true;path=[];pet.position.set(0,0,2);guardian.position.set(-1,0,2);$('#townTitle').textContent=places.find(p=>p.id===id).name;$('#townBack').textContent='Town';$('#townTalk').hidden=false;$('#townSports').hidden=id!=='school';$('.town-stops').hidden=true;const f=box(8,.15,7,'#cfa875',0,-.1,0,interior);f.userData.ground=true;box(8,3,.12,'#f1e3c6',0,1.45,-3.5,interior);box(.12,3,7,'#f1e3c6',-4,1.45,0,interior);
  (stories[id]||[]).forEach((d,i)=>{const x=-2.5+i*2.5,g=new T.Group();g.userData.action=i;interior.add(g);g.position.set(x,0,-1.4);box(1.4,.7,1,'#9f7955',0,.35,0,g);
   if(id==='library'){for(let j=0;j<5;j++)box(.13,.45,.4,['#759cb0','#dba879','#8bad8b'][j%3],-.4+j*.2,.94,0,g);}
   else if(id==='airport'){box(.7,.7,.35,i===1?'#7492aa':'#bd876b',0,1.1,0,g);box(.3,.1,.1,'#5f5647',0,1.49,0,g);}
   else if(id==='shop'){for(let j=0;j<3;j++)orb(.2,i===0?'#d9775c':i===1?'#95b8aa':'#ddb962',-.35+j*.35,.9,0,g);}
   else if(id==='cafe'){const plate=new T.Mesh(new T.CylinderGeometry(.45,.45,.06,24),mat('#fff2db'));plate.position.y=.77;g.add(plate);orb(.24,i===1?'#a7d7da':'#dfa55d',0,.96,0,g);}
   else {orb(.35,['#d794a3','#a2c29c','#e4bd77'][i],0,1,0,g);}
   const models={library:['desk','bookcaseClosedWide','table'],shop:['kitchenCabinet','cabinetTelevision','desk'],airport:['loungeSofa','desk','loungeChairRelax'],cafe:['kitchenStoveElectric','kitchenCoffeeMachine','table'],school:['desk','bookcaseClosedWide','table'],park:['bench','table','planter']};
   const old=[...g.children];asset(models[id][i],g,{width:1.65,alive:()=>alive&&interior.visible,onReady:()=>old.forEach(o=>{g.remove(o);o.geometry?.dispose();o.material?.dispose();})});
   if(id==='library')asset('books',g,{width:i===1?1.1:.45,y:i===1?.7:.87,alive:()=>alive});
   if(id==='shop'&&i===0)for(let j=0;j<3;j++)asset('apple',g,{width:.23,x:-.35+j*.35,y:.95,alive:()=>alive});
   if(id==='shop'&&i===2)asset('computerScreen',g,{width:.65,y:.9,alive:()=>alive});
   if(id==='cafe'&&i===2)asset('burger-cheese',g,{width:.5,y:.83,alive:()=>alive});
   label(d[0],0,1.95,0,g).scale.set(2.5,.5,1);
  });asset('pottedPlant',interior,{width:.7,x:2.9,z:-2.8,alive:()=>alive});asset('lampRoundFloor',interior,{width:.6,x:-3.2,z:2.5,alive:()=>alive});const npc=new T.Group();npc.position.set(0,0,-2.3);npc.scale.setScalar(.9);npc.rotation.y=-.35;npc.userData.npc=true;interior.add(npc);npcRig=attachPet(npc,{species:id==='clinic'?'cat':'dog',breed:id==='clinic'?'cat':id==='hotel'?'corgi':'shiba',outfit:'mint'},()=>alive&&inside===id);const npcLabel=label((D.locations.find(l=>l.id===id)?.npc||'마을 친구')+' · 말 걸기',0,2.8,-2.3,interior);npcLabel.userData.npc=true;asset('desk',interior,{width:1.8,x:0,z:-1,alive:()=>alive&&inside===id});if(id==='hotel'||id==='clinic'){asset('bedSingle',interior,{width:2.2,x:2.4,z:-1.6,alive:()=>alive&&inside===id});asset('bookcaseClosedWide',interior,{width:1.5,x:-2.4,z:-2.5,alive:()=>alive&&inside===id});}if(id==='school'){const sign=label('체육대회 참가',2.5,1.2,1.5,interior);sign.userData.sports=true;}tip('직원에게 다가가 말을 걸어 보세요.');save();
 }


 function prepareSports(){sportArena=true;sportPhotos=[];interior.children.forEach(o=>o.visible=false);box(8,.15,7,'#b4d69b',0,-.1,0,interior);for(const z of [.1,1.4])box(6,.025,.06,'#fff8dd',0,.02,z,interior);for(const x of [-2.8,2.8]){box(.08,.6,.08,'#ffae69',x,.3,.8,interior);label(x<0?'출발':'도착',x,1.2,.8,interior).scale.set(1.3,.35,1);}box(.12,.55,.12,'#edb968',0,.28,.2,interior);box(.12,.55,.12,'#edb968',0,.28,1.3,interior);box(.12,.1,1.2,'#faf3db',0,.55,.75,interior);sportBall=orb(.22,'#ef9867',-1.5,.5,.8,interior);asset('planter',interior,{width:1,x:2.5,z:-1.2,alive:()=>alive&&sportArena});pet.position.set(-2,0,.8);tip('달리기 · 장애물 넘기 · 공놀이');}
 function animateSport(event){if(event===2)pet.position.set(-1.5,0,.8);return new Promise(resolve=>{sportMotion={event,t:0,resolve};});}

 function approachSports(){if(locked||inside!=='school')return;navigate(2,1.5);npcPending='school-sports';}
 function approachNpc(){if(locked||!inside)return;navigate(-1.4,.5);npcPending=true;tip('직원에게 다가가는 중…');}
 function conversation(requested){
  const panel=$('.town-activity');let current=C.current(state);
  if(current&&current.episode.location!==inside){tip('진행 중인 이야기가 있어요. '+(D.locations.find(l=>l.id===current.episode.location)?.name||'그 장소')+'에서 이어가 주세요.');return;}
  if(!current){const available=D.episodes.filter(e=>e.location===inside&&e.level<=C.level(state));const e=(requested?available.find(e=>e.id===requested):null)||available.find(e=>!state.claimed.includes(state.day+':'+e.id))||available[0];if(!e){tip(D.episodes.some(e=>e.location===inside)?'아직 준비 중인 여행이에요. 레벨을 더 올린 뒤 직원과 이야기해 주세요.':'주변 물건을 눌러 함께 놀아 보세요.');return;}const r=C.begin(state,e.id);if(!r.ok){tip(window.KittyI18n?.t(r.message)||r.message);return;}save();current=C.current(state);}
  if(current.episode.id==='school-sports'&&!sportArena)prepareSports();const token=++activityId;locked=true;panel.hidden=false;panel.classList.add('npc-conversation');panel.innerHTML='<button class="town-dismiss" aria-label="대화 닫기">×</button><small class="npc-name"></small><h3></h3><button class="town-hear">다시 듣기</button><button class="town-translate">해석 보기</button><p class="town-ko" hidden></p><div class="town-answers"></div><p class="town-feedback" role="status"></p><button class="npc-next primary" hidden>계속</button>';
  const valid=()=>alive&&token===activityId&&!panel.hidden;
  const dismiss=()=>{activityId++;locked=false;panel.hidden=true;window.KittySpeech.stop();};panel.querySelector('.town-dismiss').onclick=dismiss;
  panel.querySelector('.npc-name').textContent=(D.locations.find(l=>l.id===inside)?.npc||'친구')+' · '+(state.active.index+1)+' / '+current.episode.nodes.length;
  const line=C.expand(state,current.node.line);panel.querySelector('h3').textContent=line;panel.querySelector('.town-ko').textContent=D.translations[current.node.id]||'';
  panel.querySelector('.town-translate').onclick=()=>{panel.querySelector('.town-ko').hidden=!panel.querySelector('.town-ko').hidden;};
  let reading=false;const next=panel.querySelector('.npc-next'),answers=panel.querySelector('.town-answers');
  async function read(text){reading=true;next.disabled=true;answers.querySelectorAll('button').forEach(b=>b.disabled=true);panel.querySelector('.town-hear').disabled=true;try{await speak(text);}finally{if(valid()){reading=false;next.disabled=false;panel.querySelector('.town-hear').disabled=false;answers.querySelectorAll('button').forEach(b=>b.disabled=!!state.active?.accepted);}}}
  panel.querySelector('.town-hear').onclick=()=>read(line);
  current.node.choices.forEach((choice,index)=>{const b=document.createElement('button');b.textContent=C.expand(state,choice.text);answers.append(b);b.onclick=async()=>{if(reading||!valid()||state.active.accepted)return;const r=C.answer(state,index);save();if(r.retreat){dismiss();tip('잠깐 쉬었다 다시 도전해요.');return;}b.classList.add(r.ok?'right':'wrong');if(!r.ok){wrong();panel.querySelector('.town-feedback').textContent='다시 듣고 따라 해 봐요.';await read(C.expand(state,current.node.choices.find(c=>c.ok).text));return;}panel.querySelector('.town-feedback').textContent='잘했어요!';await Promise.all([read(b.textContent),current.episode.id==='school-sports'?animateSport(state.active.index):Promise.resolve()]);if(valid())next.hidden=false;};});
  next.onclick=()=>{if(reading)return;const r=C.next(state);if(r.finished&&r.episode==='school-sports'&&r.memory&&sportPhotos.filter(Boolean).length===3)r.memory.photos=[...sportPhotos];save();if(!r.ok)return;if(!r.finished){conversation();return;}activityId++;panel.innerHTML='<h3>이야기 완료!</h3><div class="npc-reward"></div><p>추억 사진 3장이 앨범에 담겼어요.</p><button class="primary">계속 둘러보기</button>';panel.querySelector('.npc-reward').textContent='+'+r.gold+' 골드 · +'+r.xp+' 경험치';panel.querySelector('button').onclick=()=>{locked=false;panel.hidden=true;if(sportArena)enter('school');};};
  if(state.active.accepted){next.hidden=false;answers.querySelectorAll('button').forEach(b=>b.disabled=true);}else read(line);
 }

 function leave(){sportMotion?.resolve();sportMotion=null;pet.position.y=0;activityId++;inside=null;host.dataset.inside='';npcPending=false;path=[];interior.visible=false;outside.visible=true;$('.town-activity').hidden=true;locked=false;collectMode=null;$('#townTitle').textContent='A walk together';$('#townBack').textContent='Home';$('#townTalk').hidden=true;$('#townSports').hidden=true;$('.town-stops').hidden=false;const p=places.find(p=>p.id===pending);pet.position.set(p?.door.x||0,0,(p?.door.z||7)+1);pending=null;tip('Where shall we go next?');}
 $('#townBack').onclick=()=>{window.KittySpeech.stop();inside?leave():onHome();};$('#townTalk').onclick=approachNpc;$('#townSports').onclick=approachSports;for(const p of places){const b=document.createElement('button');b.textContent=p.name;b.dataset.destination=p.id;b.onclick=()=>navigate(p.door.x,p.door.z,p.id);$('.town-stops').append(b);}
 renderer.domElement.onpointerdown=e=>{if(!$('.town-activity').hidden)return;const r=renderer.domElement.getBoundingClientRect();pointer.set((e.clientX-r.left)/r.width*2-1,-(e.clientY-r.top)/r.height*2+1);ray.setFromCamera(pointer,camera);const hits=ray.intersectObjects((inside?interior:outside).children,true);for(const h of hits){let o=h.object;if(o.userData.collect){if(!o.visible||!collectMode)return;o.removeFromParent();o.geometry.dispose();o.material.dispose();collectMode.count++;tip('Collected '+collectMode.count+' / 3');if(collectMode.count===3){tip('All done! '+reward(collectMode.location+':collect'));collectMode=null;}return;}while(o&&o!==scene){if(inside&&o.userData.sports){approachSports();return;}if(inside&&o.userData.npc){approachNpc();return;}if(inside&&o.userData.action!==undefined){activity(o.userData.action);return;}if(!inside&&o.userData.place){const p=places.find(p=>p.id===o.userData.place);navigate(p.door.x,p.door.z,p.id);return;}o=o.parent;}if(h.object.userData.ground){navigate(h.point.x,h.point.z);return;}}};
 const resize=()=>{const r=host.getBoundingClientRect();renderer.setSize(r.width,r.height);camera.aspect=r.width/r.height;camera.updateProjectionMatrix()};const ro=new ResizeObserver(resize);ro.observe(host);resize();
 function tick(t){if(!alive)return;const dt=last?Math.min((t-last)/1000,.04):0;last=t;if(document.hidden){frame=requestAnimationFrame(tick);return}const moving=path.length>0&&!locked;if(moving){const next=path[0],dx=next.x-pet.position.x,dz=next.z-pet.position.z,d=Math.hypot(dx,dz);if(d<.09)path.shift();else{const s=Math.min(d,dt*3);pet.position.x+=dx/d*s;pet.position.z+=dz/d*s;pet.rotation.y=Math.atan2(dx,dz);}}if(!path.length&&pending&&!inside&&!arrived){arrived=true;enter(pending);}if(!path.length&&npcPending&&inside){const request=npcPending;npcPending=false;conversation(typeof request==='string'?request:null);}npcRig?.update(dt,false,false);if(sportMotion){const m=sportMotion;m.t+=dt;const k=Math.min(1,m.t/2);if(m.event<2){pet.position.set(-2+4*k,m.event===1?Math.sin(k*Math.PI)*1.3:0,.8);pet.rotation.y=Math.PI/2;}else{sportBall.position.set(2.5-4*k,.6+Math.sin(k*Math.PI)*2,-1.2+2*k);}if(k===1){renderer.render(scene,camera);sportPhotos[m.event]=renderer.domElement.toDataURL('image/jpeg',.7);sportMotion=null;m.resolve();}}rig.update(dt,moving||!!sportMotion,true);const gp=pet.position.clone().add(new T.Vector3(-Math.cos(pet.rotation.y)*1.05,0,Math.sin(pet.rotation.y)*1.05));const gd=gp.distanceTo(guardian.position);guardian.position.lerp(gp,Math.min(1,dt*5));guardian.rotation.y=pet.rotation.y;guardianRig.update(dt,moving||gd>.15,false);host.dataset.guardian=guardianRig.ready?'ready':'loading';const lp=leashGeometry.attributes.position;lp.setXYZ(0,guardian.position.x+.28,1.4,guardian.position.z+.22);lp.setXYZ(1,(guardian.position.x+pet.position.x)/2,.7,(guardian.position.z+pet.position.z)/2);lp.setXYZ(2,pet.position.x,.8,pet.position.z);lp.needsUpdate=true;leashGeometry.computeBoundingSphere();leash.visible=!inside;guardian.visible=!inside;host.dataset.petAsset=rig.ready?'ready':'loading';if(inside){look.lerp(new T.Vector3(0,$('.town-activity').hidden?.8:-1,-.8),Math.min(1,dt*5));camera.position.lerp(new T.Vector3(5,7,11),Math.min(1,dt*5));}else{look.lerp(pet.position.clone().add(new T.Vector3(0,.7,0)),Math.min(1,dt*5));camera.position.lerp(pet.position.clone().add(new T.Vector3(8,15,14)),Math.min(1,dt*5));}camera.lookAt(look);renderer.render(scene,camera);frame=requestAnimationFrame(tick);}
 camera.position.set(8,11,20);stop=()=>{alive=false;sportMotion?.resolve();cancelAnimationFrame(frame);ro.disconnect();scene.traverse(o=>{o.geometry?.dispose();for(const m of [].concat(o.material||[])){m.map?.dispose();m.dispose();}});renderer.dispose();renderer.forceContextLoss();host.hidden=true;};frame=requestAnimationFrame(tick);if(destination){const dest=places.find(p=>p.id===destination);if(dest)navigate(dest.door.x,dest.door.z,dest.id);}
}
window.KittyTown={open:openTown,close:()=>stop()};
