(()=>{'use strict';
const bank=[
['home',1,'I need water.','물이 필요해요.','water','물',['milk','food']],['home',1,'Good morning!','좋은 아침이에요!','morning','아침',['night','home']],['home',2,'I am going home.','집에 가고 있어요.','home','집',['school','shop']],
['cafe',1,'Yes, water, please.','네, 물 주세요.','water','물',['bread','milk']],['cafe',1,'Thank you!','고마워요!','thank','감사하다',['want','have']],['cafe',2,'A table for two, please.','두 명이 앉을 자리를 주세요.','table','식탁',['chair','plate']],
['airport',1,'I have one bag.','가방이 하나 있어요.','bag','가방',['key','book']],['airport',2,'Here is my passport.','여기 제 여권이 있어요.','passport','여권',['ticket','bag']],['airport',2,'Two tickets, please.','표 두 장 주세요.','tickets','표들',['books','keys']],
['hotel',1,'Here is a towel.','여기 수건이 있어요.','towel','수건',['pillow','soap']],['hotel',2,'I have a room key.','방 열쇠가 있어요.','key','열쇠',['bag','bed']],['hotel',3,'My room is upstairs.','제 방은 위층에 있어요.','upstairs','위층에',['outside','downstairs']],
['clinic',1,'I need water.','물이 필요해요.','water','물',['food','milk']],['clinic',2,'I have a fever.','열이 있어요.','fever','열',['towel','ticket']],['clinic',3,'Thank you for your help.','도와주셔서 고마워요.','help','도움',['room','bag']],
['school',1,'Yes, I am ready.','네, 준비됐어요.','ready','준비된',['hungry','sleepy']],['school',2,'I need a red block.','빨간 블록이 필요해요.','red','빨간색',['blue','green']],['school',3,'Here is the red block.','여기 빨간 블록이 있어요.','block','블록',['book','bag']],
['library',1,'Yes, a picture book, please.','네, 그림책 주세요.','book','책',['bag','ball']],['library',2,'Yes, a picture book, please.','네, 그림책 주세요.','picture','그림',['window','water']],['shop',1,'Yes, a bag, please.','네, 봉투 주세요.','bag','봉투',['bed','book']],['shop',2,'Yes, I need pet food.','네, 반려동물 사료가 필요해요.','food','음식',['room','key']],['park',1,'Yes, I can help.','네, 도울 수 있어요.','help','돕다',['sleep','eat']],['park',2,'Yes, let’s go together.','네, 함께 가요.','together','함께',['upstairs','outside']]
].map(([location,level,en,ko,word,meaning,distractors])=>({location,level,en,ko,word,meaning,distractors}));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;};
function sentence(mount,{text,prompt='단어를 골라 답해요.',onComplete=()=>{},onWrong=()=>{},canInteract=()=>true}){
 const words=text.trim().split(/\s+/);let at=0,done=false;mount.innerHTML='';mount.classList.add('word-game');const title=document.createElement('p');title.className='word-prompt';title.textContent=prompt;const tray=document.createElement('div');tray.className='word-tray';tray.setAttribute('aria-live','polite');const tiles=document.createElement('div');tiles.className='word-tiles';const feedback=document.createElement('p');feedback.className='word-feedback';feedback.setAttribute('role','status');const hint=document.createElement('button');hint.className='word-hint';hint.textContent='힌트 보기';hint.onclick=()=>{if(canInteract()&&!done)feedback.textContent=text;};mount.append(title,tray,tiles,feedback,hint);
 function show(){tray.textContent=words.slice(0,at).join(' ')||'여기에 문장을 완성해요';}
 shuffle(words.map((word,id)=>({word,id}))).forEach(({word,id})=>{const b=document.createElement('button');b.className='word-tile';b.dataset.token=id;b.textContent=word;b.onclick=()=>{if(done||!canInteract()||b.dataset.used)return;if(word!==words[at]){b.classList.add('wrong');feedback.textContent='순서를 다시 생각해 봐요. 고른 단어는 그대로 남아 있어요.';onWrong();return;}b.dataset.used='true';b.disabled=true;b.classList.remove('wrong');at++;show();feedback.textContent='';if(at===words.length){done=true;feedback.textContent='완성! 문장을 들어 보세요.';onComplete(text);}};tiles.append(b);});show();return {get complete(){return done;}};
}
function start(type,mount,api){let alive=true,round=0,busy=false;const level=api.level||1,location=api.location||'home';let local=bank.filter(q=>q.location===location&&q.level<=level);const rest=shuffle(bank.filter(q=>q.level<=level&&!local.includes(q)));const questions=[...shuffle(local),...rest].slice(0,3);mount.innerHTML='<div class="word-game-head"><b></b><span></span></div><div class="word-round"></div><p class="word-round-status" role="status"></p>';const host=mount.querySelector('.word-round'),progress=mount.querySelector('.word-game-head span'),status=mount.querySelector('.word-round-status');mount.querySelector('.word-game-head b').textContent=type==='sentence'?'문장 만들기':'단어 맞추기';
 async function completed(text){if(busy||!alive)return;busy=true;status.textContent=text+' · 발음을 듣고 있어요…';const result=await api.speak(text);if(!alive)return;if(result==='error'||result==='cancelled'){status.textContent='발음을 다시 들으면 이어집니다.';const b=document.createElement('button');b.textContent='다시 듣기';b.className='secondary';b.onclick=()=>{b.remove();busy=false;completed(text);};status.append(b);return;}round++;busy=false;if(round<questions.length){draw();return;}host.innerHTML='';progress.textContent='3 / 3';const paid=api.finish(true);status.textContent=paid?'완료! +15 골드 · +20 경험치':'완료! 오늘 보상은 이미 받았어요.';const back=document.createElement('button');back.className='primary';back.textContent='계속 둘러보기';back.onclick=api.exit;host.append(back);}
 function draw(){if(!alive)return;status.textContent='';progress.textContent=(round+1)+' / 3';const q=questions[round];if(type==='sentence'){sentence(host,{text:q.en,prompt:q.ko,onComplete:completed,onWrong:api.wrong,canInteract:()=>alive&&!busy});return;}host.className='word-round word-game';host.innerHTML='';const prompt=document.createElement('p');prompt.className='word-prompt';prompt.textContent=q.meaning+'에 맞는 영어 단어는?';const tiles=document.createElement('div');tiles.className='word-tiles';host.append(prompt,tiles);shuffle([q.word,...q.distractors]).forEach(word=>{const b=document.createElement('button');b.className='word-tile';b.textContent=word;b.onclick=()=>{if(busy||!alive)return;if(word!==q.word){b.classList.add('wrong');status.textContent='다시 골라 보세요.';api.wrong();return;}b.classList.add('right');completed(q.en);};tiles.append(b);});}
 draw();return ()=>{alive=false;};
}
window.KittyWordGames={sentence,start,bank};})();
